apis/outlook/calendar/manage/openapi.yaml, apis/outlook/calendar/read/openapi.yaml, apis/outlook/mail/manage/openapi.yaml, apis/outlook/mail/read/openapi.yaml
This will help the model understand what the APIs are for.
=> fix: outlook: improve OpenAPI titles

apis/notion/read/tool.gpt, apis/notion/write/tool.gpt, apis/outlook/calendar/manage/tool.gpt, apis/outlook/calendar/read/tool.gpt, apis/outlook/mail/manage/tool.gpt, apis/outlook/mail/read/tool.gpt, apis/slack/read/tool.gpt, apis/slack/write/tool.gpt, apis/supabase/read-only/tool.gpt, apis/supabase/read-write/tool.gpt, apis/trello/tool.gpt, clis/redis-cli/tool.gpt
This will make searching for these tools easier on tools.gptscript.ai.
=> add descriptions to tools that didn't have them

apis/outlook/mail/manage/tool.gpt, apis/outlook/mail/read/tool.gpt
=> add prompting for Outlook to avoid printing HTML

apis/hubspot/marketing/hubspot-marketing.yaml, apis/hubspot/marketing/tool.gpt
Signed-off-by: Taylor Price <tayworm@gmail.com>
=> chore: initial commit of hubspot marketing tools

apis/slack/code/index.js, apis/slack/code/src/tools.js, apis/slack/code/tool.gpt, apis/slack/read/tool.gpt, apis/slack/write/tool.gpt
for gptscript-ai/desktop#316
This PR adds several more tools to Slack in order to make it more feature complete. We can now interact with private channels, DMs, and threads.
=> improve slack tools

apis/outlook/calendar/manage/tool.gpt, apis/outlook/calendar/read/tool.gpt, apis/outlook/mail/manage/tool.gpt, apis/outlook/mail/read/tool.gpt
=> fix: outlook: ask LLM not to output IDs

apis/outlook/mail/code/pkg/printers/mail.go
=> fix: outlook mail: include links to messages

apis/outlook/mail/manage/tool.gpt, apis/outlook/mail/read/tool.gpt
for https://github.com/gptscript-ai/desktop/issues/361
=> outlook mail: tell the LLM to print links

apis/outlook/mail/manage/tool.gpt, apis/outlook/mail/read/tool.gpt
for gptscript-ai/desktop#361
I tested this, and now it formats them better. I should have listened to the comments on my last PR for this, lol.
=> outlook mail: tell the LLM to use Markdown

apis/hubspot/crm/read/tool.gpt, apis/hubspot/crm/write/tool.gpt
Signed-off-by: Taylor Price <tayworm@gmail.com>
=> chore: improvements to prompts

apis/github/code/index.js, apis/github/code/src/tools.js, apis/github/code/tool.gpt, apis/github/read/tool.gpt, apis/github/write/tool.gpt
=> Enhance: add star count

apis/notion/code/context.gpt, apis/notion/code/index.js, apis/notion/code/src/database.js, apis/notion/code/src/search.js, apis/notion/code/src/users.js, apis/notion/code/tool.gpt, apis/notion/read/tool.gpt, apis/notion/write/tool.gpt
This PR adds four new tools for Notion, mostly to support writing to databases. I also introduced various other improvements to the code, including removing the `share credential` lines and instead defining the credential in each individual tool.
=> enhance: add more notion tools

apis/google/gmail/code/readEmail.py
relates to https://github.com/gptscript-ai/otto/issues/97
=> fix: properly parse parts on emails with attachments

apis/google/gmail/code/tool.gpt
relates to https://github.com/gptscript-ai/otto/issues/98
=> fix: properly handle subject and body of forwarded email

apis/slack/code/tool.gpt, apis/slack/read/tool.gpt, apis/slack/write/tool.gpt
These tools will be more useful for my step templates with the credential defined on each one.
=> chore: slack: define credentials on each tool

github/index.js, github/src/tools.js, github/tool.gpt
- Share github tool dependencies to make tools "self-contained"; i.e. Each tool
can be imported and used without manually importing other tools
- Rename deleteIssue/PR to closeIssue/PR
- Reorganize tool and function definition order to match across .gpt
file and JS files
- Add the github "bundle" tool
=> enhance: make github tools self-contained

notion/tool.gpt
- Make notion tool self-contained s.t. the necessary tools to
discover required parameters are shared
- Add the notion tool bundle
=> enhance: make notion tools self-contained

slack/tool.gpt
- Share slack tool dependencies to make tools "self-contained"; i.e. Each tool can be imported and used without manually importing other tools
- Add tool "bundle" for slack
=> enhance: make slack tools self-contained

outlook/calendar/tool.gpt
- **enhance: make outlook calendar self-contained**
- **enhance: add outlook calendar tool bundle**
=> enhance: make outlook calendar self-contained

outlook/mail/tool.gpt
- **enhance: make outlook mail tools self-contained**
- **enhance: add outlook mail tool bundle**
=> enhance: make outlook mail tools self-contained

google/youtube/tool.gpt
- Rename tools and descriptions to more accurately convey their purpose
- Attempt to generate a transcript when one isn't available from YouTube
- Add tool and associated metadata to bundle all YouTube related tools
=> enhance: add youtube bundle tool and metadata

google/sheets/tool.gpt
- **enhance: make google spreadsheet tools self-contained**
- **enhance: add google sheets tool bundle**
=> enhance: make google spreadsheet tools self-contained

google/youtube/tool.gpt
Darren told me that this is a change we need to make.
=> fix: use credential keyword for credential references

time/tool.gpt
Add the `Current Date and Time` context tool along with a new `Time` tool category.
=> enhance: add current date and time context tool

google/gmail/tool.gpt
relates to https://github.com/otto8-ai/otto8/issues/98 and https://github.com/otto8-ai/otto8/issues/99
=> chore: instruct the "Send Email" tool that it cannot forward or reply to emails

images/.eslintignore, images/.eslintrc.cjs, images/.gitignore, images/package-lock.json, images/package.json, images/src/analyze.ts, images/src/generate.ts, images/src/tools.ts, images/tool.gpt, images/tsconfig.json, index.yaml
Add an `Images` tool bundle with tools for image generation and analysis.
Note: Open to suggestions on better names for this bundle.
=> feat: add vision and image generation tools

google/docs/auth.py, google/docs/credential/tool.gpt, google/docs/id.py, google/docs/list_docs.py, google/docs/read_doc.py, google/docs/requirements.txt, google/docs/tool.gpt, index.yaml
Add initial Google Docs tool bundle with the ability to list documents and get their contents in markdown format.
Note: Search, create, update, and delete not yet supported.
=> feat: add google docs tools

github/tool.gpt, google/gmail/tool.gpt, outlook/calendar/tool.gpt, outlook/mail/tool.gpt, slack/tool.gpt
- **enhance: share time context for github tools**
- **enhance: share time context for gmail tools**
- **enhance: share time context for slack tools**
- **enhance: share time context for outlook calendar tools**
- **enhance: share time context for outlook mail tools**
Addresses https://github.com/otto8-ai/otto8/issues/237
=> enhance: share time context where helpful

index.yaml, knowledge/data-sources/notion/src/index.ts, knowledge/data-sources/onedrive/main.go, knowledge/data-sources/website/colly.go, knowledge/data-sources/website/main.go
This PR fixed some sync related bugs and also support new Knowledge UX revamp.
=> Fix: fix sync tool bugs

knowledge/data-sources/onedrive/main.go
This pr fixed a panic error that is not intended.
=> Fix: fix nil pointer bug

excel/tool.gpt
relates to https://github.com/otto8-ai/otto8/issues/231
=> fix: do not automatically select workbook if not told to

google/gmail/helpers.py, google/gmail/requirements.txt, google/gmail/tool.gpt
I added a bit of context to make the LLM behave better.
=> chore: gmail: bump py-gptscript

outlook/calendar/pkg/commands/listEvents.go, outlook/calendar/pkg/commands/searchEvents.go
Only doing this for the sake of consistency.
=> chore: use underscores in dataset names

google/gmail/helpers.py, outlook/mail/pkg/commands/listMessages.go
The dataset tools have been updated to preserve the order of data, so I am reintroducing datasets to these tools that I had previously removed them from.
=> chore: reintroduce datasets

knowledge/data-sources/notion/package-lock.json, knowledge/data-sources/notion/package.json, knowledge/data-sources/notion/src/index.ts, knowledge/data-sources/notion/src/page.ts, knowledge/data-sources/notion/tool.gpt, knowledge/data-sources/notion/tsconfig.json, knowledge/data-sources/onedrive/main.go, knowledge/data-sources/website/colly.go, knowledge/data-sources/website/main.go
1. Convert notion to new tool format.
2. Fixed bugs and cleaned up the code in onedrive and website.
=> Chore: Convert notion, tweak onedrive/website

.gitignore, knowledge/data-sources/notion/credential/tool.gpt, knowledge/data-sources/notion/tool.gpt, knowledge/data-sources/onedrive/credential/tool.gpt, knowledge/data-sources/onedrive/main.go, knowledge/data-sources/onedrive/tool.gpt
This change also fixes a small bug in the onedrive connector.
=> chore: make the data source credentials similar to other credentials

browser/package-lock.json, browser/package.json, browser/src/screenshot.ts, browser/src/server.ts, browser/src/session.ts, browser/tool.gpt
Added a gptscript tool to take the screenshot of a tabID
Added API endopoint for tool to communicate with.
Added new method to take the screenshot and store in the workspace.
=> enhance: add screenshot tool

google/search/package.json, google/search/src/context.ts, google/search/src/search.ts, google/search/src/server.ts, google/search/src/session.ts, google/search/tool.gpt
Run the google search tool as a daemon and use the updated ephemeral session
management similar to the logic used by the browser tool.
Note: All users share a single browser session.
=> enhance: run google search tool as a daemon

knowledge/pkg/datastore/defaults/defaults.go, knowledge/pkg/datastore/documentloader/pdf/mupdf/pdf.go, knowledge/pkg/datastore/textsplitter/markdown_basic/options.go, knowledge/pkg/datastore/textsplitter/textsplitter.go
ref https://github.com/otto8-ai/otto8/issues/380
=> fix: do not error on single page pdf within chunksize boundaries

images/package-lock.json, images/package.json, images/src/generate.ts
Download generated images and store them with the workspace API
Note: The generate images tool now returns the file path in the workspace instead of an external URL.
=> enhance: use workspaces for storing generating images

excel/tool.gpt, google/docs/tool.gpt, google/gmail/tool.gpt, google/search/tool.gpt, google/sheets/tool.gpt, google/youtube/tool.gpt, outlook/calendar/tool.gpt, outlook/mail/tool.gpt
This has a sibling PR that adds the assets to the admin.
https://github.com/otto8-ai/otto8/pull/401
=> feat: update relevant icons to be colorful

outlook/calendar/pkg/printers/events.go
partial solution for https://github.com/otto8-ai/otto8/issues/170
=> fix: add attendee responses and recurring info to detailed output

outlook/mail/credential/tool.gpt, outlook/mail/main.go, outlook/mail/pkg/commands/getDefaultTimezone.go, outlook/mail/pkg/global/global.go, outlook/mail/tool.gpt
This is useful if the user asks some time-related question, like "list inbox messages from last week" or something.
=> enhance: outlook mail: include default time zone

outlook/mail/main.go, outlook/mail/pkg/commands/searchMessages.go, outlook/mail/pkg/graph/mail.go, outlook/mail/pkg/printers/mail.go, outlook/mail/tool.gpt
This adds dataset support and a `limit` parameter to the tool for searching for emails.
=> enhance: outlook mail: search messages: dataset and limit parameter

knowledge/pkg/vectorstore/pgvector/pgvector.go
=> fix: nil-pointer in pgvector

knowledge/pkg/vectorstore/pgvector/pgvector.go
This should address https://github.com/otto8-ai/otto8/issues/510
=> fix: make pgvector WHERE clauses safer by switching to prepared statements

knowledge/pkg/cmd/client.go, knowledge/pkg/cmd/ingest.go, knowledge/pkg/cmd/load.go, knowledge/pkg/datastore/defaults/defaults.go, knowledge/pkg/datastore/documentloader/ocr/openai/openai.go, knowledge/pkg/datastore/documentloader/smartpdf/smartpdf.go, knowledge/pkg/datastore/embeddings/openai/openai.go
Ref https://github.com/otto8-ai/otto8/issues/454
=> enhance: knowledge - logs and increased/configurable openai api timeouts

slack/tool.gpt
=> fix: slack: improve prompting around user context tool

outlook/mail/tool.gpt
depends on https://github.com/gptscript-ai/datasets/pull/13
=> fix: list totals when working with datasets

bluesky/src/posts.ts, bluesky/src/tools.ts, bluesky/tool.gpt
Add a `Create Post` tool to the `Bluesky` bundle to allow agents to create new posts.
=> enhance: enable creating bluesky posts

bluesky/src/posts.ts, bluesky/src/tools.ts, bluesky/tool.gpt
Add a `Delete Post` tool to the `Bluesky` bundle to allow agents to delete posts by URI.
**Note: will drop the commit to create posts when #234 merges**
=>  enhance: enable deleting bluesky posts

knowledge/pkg/config/config.go, knowledge/pkg/datastore/datastore.go
Paths up for discussion - this is still from when it was used as a standalone tool.
I guess we don't care too much though :grimacing:
=> change: (breaking) make sqlite/sqlite-vec the default index/vector DB config

knowledge/pkg/index/sqlite/sqlite.go, knowledge/pkg/vectorstore/sqlite-vec/sqlite-vec.go
There's more to be done - just pushing this out before the release as it's a tiny improvement and doesn't make things worse
=> change: enable sqlite pragmas to help with concurrency (db locking) problems

knowledge/pkg/index/sqlite/sqlite.go, knowledge/pkg/vectorstore/sqlite-vec/sqlite-vec.go
This reverts commit 09112d452afb85a7d50d28a60e50cb0816616ad5.
=> Revert "change: enable sqlite pragmas to help with concurrency problems"

knowledge/go.mod, knowledge/go.sum, knowledge/pkg/index/sqlite/sqlite.go, knowledge/pkg/vectorstore/sqlite-vec/sqlite-vec.go
Same as before, but without WAL as that seems to break in our setup.
=> fix: sqlite/-vec busy_timeout to help with db locking issue

excel/main.go, excel/pkg/commands/addWorksheetColumn.go, excel/pkg/commands/addWorksheetRow.go, excel/pkg/graph/worksheet.go, excel/tool.gpt
- also adds the ability to add a new column
=> chore: enable working with formulas when adding new rows or columns

knowledge/pkg/datastore/documentloader/defaults.go, knowledge/pkg/datastore/filetypes/filetypes.go, knowledge/pkg/flows/config/blueprints/otto.yaml
Ref https://github.com/otto8-ai/otto8/issues/469
=> remove: drop support for .zip and .bz2 (and related mimetypes) + support .pages

knowledge/pkg/datastore/embeddings/openai/openai.go
This reverts commit 53542f56c49e51c4f72ed0b89c9a666c697e96ec.
=> Revert "Fix: Increase timout to 4 minutes, increase overall timeout 

knowledge/data-sources/onedrive/main.go
https://github.com/otto8-ai/otto8/issues/538
Refactored the code a bit so that when fetch children files from folder, start syncing immediately so that user will see file showing up in UI.
=> Fix: refactored onedrive to download file when syncing metadata

anthropic-model-provider/requirements.txt, knowledge/pkg/datastore/documentloader/ocr/openai/openai.go
depends on https://github.com/gptscript-ai/claude3-provider-common/pull/5
Ref https://github.com/otto8-ai/otto8/issues/813
=> fix: support the claude/anthropic provider's vision response

images/src/analyze.ts, images/tool.gpt
Addresses https://github.com/obot-platform/obot/issues/937
=> enhance: support analyzing webp images

images/package-lock.json, images/package.json, images/src/analyze.ts, images/src/generate.ts, images/tool.gpt
- Change the `Generate Images` tool to produce webp images instead of
png
- Tweak the `Generate Images Context` to improve the UX for displaying
generated images in the UI
- Tweak the `Analyze Images Context` to improve the LLM's reliability
when constructing the `images` argument when analyzing a single image
Addresses https://github.com/obot-platform/obot/issues/936
Depends on https://github.com/obot-platform/tools/pull/287
=> enhance: generate webp images 

knowledge/pkg/datastore/embeddings/openai/openai.go, website-cleaner/main.go
... quick fix until this is changed to use gptscript-go now that we have retries there
=> fix: only return last retry error - log the rest

atlassian/credential/tool.gpt, atlassian/jira/.gitignore, atlassian/jira/index.js, atlassian/jira/package-lock.json, atlassian/jira/package.json, atlassian/jira/src/comments.js, atlassian/jira/src/issues.js, atlassian/jira/src/priorities.js, atlassian/jira/src/projects.js, atlassian/jira/src/sites.js, atlassian/jira/src/users.js, atlassian/jira/tool.gpt, index.yaml
Add MVP Jira tools with support for:
- Issue search, create, and edit
- Listing and adding comments to an issue
- Listing projects
Addresses https://github.com/obot-platform/obot/issues/867
Supersedes https://github.com/obot-platform/tools/pull/277
**Note:** This was initially implemented in JavaScript in @tybalex's original PR, so I proceeded with that. At some point we may want to make the jump to typescript to align with the preference in this repo.
=> feat: add mvp jira tool bundle

excel/tool.gpt
relates to https://github.com/obot-platform/obot/issues/124
=> fix: clarify instructions in context

images/tool.gpt
Update the start and end of image tools contexts to align more closely
with those for other tools.
=> chore: update image tools context headers and footers

browser/tool.gpt
Depends on https://github.com/obot-platform/obot/pull/1088
=> enhance: use chromium icon for the browser bundle

outlook/calendar/pkg/printers/events.go, outlook/calendar/tool.gpt
relates to https://github.com/obot-platform/obot/issues/504
=> fix: group events coming from the same calendar

website-cleaner/main.go
We already have code base cleaning that will remove unnecessary tags, adding LLM cleaning will introduce overhead and prune to fail.
https://github.com/obot-platform/obot/issues/926
=> Fix: remove LLM cleaner

google/search/src/server.ts, google/search/src/session.ts
Addresses https://github.com/obot-platform/obot/issues/1095
=> fix: ensure that the search browser is properly terminated when obot exits

browser/src/server.ts, browser/src/session.ts
Addresses https://github.com/obot-platform/obot/issues/1094
=> fix: ensure that the browser is properly terminated when obot exits

atlassian/jira/tool.gpt, github/tool.gpt, google/docs/tool.gpt, google/gmail/tool.gpt, google/search/tool.gpt, google/sheets/tool.gpt, google/youtube/tool.gpt, notion/tool.gpt, outlook/calendar/tool.gpt, outlook/mail/tool.gpt, salesforce/tool.gpt, slack/tool.gpt
* adds oauth metadata to relevant tools
=> enhance: add oauth metadata to relevant tools

outlook/mail/credential/tool.gpt, outlook/mail/tool.gpt
relates to https://github.com/obot-platform/obot/issues/1160
=> fix: use a single credential for outlook mail

knowledge/pkg/client/client.go, knowledge/pkg/client/common.go, knowledge/pkg/client/standalone.go, knowledge/pkg/cmd/edit_dataset.go, knowledge/pkg/cmd/export.go, knowledge/pkg/cmd/get_dataset.go, knowledge/pkg/datastore/dataset.go, knowledge/pkg/datastore/ingest.go, knowledge/pkg/datastore/retrieve.go, knowledge/pkg/datastore/retrievers/bm25.go, knowledge/pkg/datastore/retrievers/retrievers.go, knowledge/pkg/datastore/retrievers/routing.go, knowledge/pkg/datastore/retrievers/subquery.go, knowledge/pkg/datastore/store/store.go, knowledge/pkg/index/db.go, knowledge/pkg/index/index.go, knowledge/pkg/index/postgres/postgres.go, knowledge/pkg/index/sqlite/sqlite.go, knowledge/pkg/index/types/models.go, knowledge/pkg/index/types/types.go
Slack discussion: https://acorn-io.slack.com/archives/C03FU91U4SX/p1736544805445689
Target query that would be generated and is not needed in 99.99% of the cases:
```sql
SELECT * FROM "documents" WHERE ("documents"."file_id","documents"."dataset") IN (($1,$2),($3,$4),($5,$6),($7,$8),($9,$10),($11,$12),($13,$14),($15,$16),($17,$18),($19,$20),($21,$22),($23,$24),($25,$26),($27,$28),($29,$30),($31,$32),($33,$34),($35,$36),($37,$38),($39,$40),($41,$42),($43,$44),($45,$46),($47,$48),($49,$50),($51,$52),($53,$54),($55,$56),($57,$58),($59,$60),($61,$62),($63,$64),($65,$66),($67,$68),($69,$70),($71,$72),($73,$74),($75,$76),($77,$78),($79,$80),($81,$82),($83,$84),($85,$86),($87,$88),($89,$90),($91,$92),($93,$94),($95,$96),($97,$98),($99,$100),($101,$102),($103,$104),($105,$106),($107,$108),($109,$1 …
```
=> enhance: (knowledge) only preload files on datasets if asked for

anthropic-bedrock-model-provider/main.py, anthropic-bedrock-model-provider/tool.gpt, anthropic-bedrock-model-provider/validate.py
=> feat: Anthropic Bedrock Model Provider Validation

knowledge/data-sources/website/colly.go
https://github.com/obot-platform/obot/issues/1210
=> Fix: limit PDF files to 100MB too

.github/workflows/package-tools.yaml
Requires: https://github.com/obot-platform/obot/pull/1314
=> chore: add CI to ensure tools can be packaged correctly

zoom/tool.gpt
Related to https://github.com/obot-platform/obot/pull/1336
Signed-off-by: Ryan Hopper-Lowe <ryan@acorn.io>
=> chore: update zoom logo location

file-summarizer/summarize.py, file-summarizer/tool.gpt
- Add the summarizer tool to `Utility` category to fix https://github.com/obot-platform/obot/issues/1350
- Add output token length limit to system prompts to fix https://github.com/obot-platform/obot/issues/1227#issuecomment-2603195258
=> fix: summarizer tool bug fix

zoom/main.py, zoom/tools/meetings.py
to address https://github.com/obot-platform/obot/issues/1354
=> fix: zoom tool bug fix

google/docs/update_doc.py
Addresses https://github.com/obot-platform/obot/issues/1425
=> fix: google docs update style

google/credential/tool.gpt, google/docs/create_doc.py, google/docs/move_doc.py, google/docs/tool.gpt, google/docs/update_doc.py
Addresses https://github.com/obot-platform/obot/issues/1491
=> enhance: add ability to create and move google docs to specific drive folders

index.yaml, linkedin/credential/tool.gpt, linkedin/main.py, linkedin/requirements.txt, linkedin/tool.gpt, linkedin/tools/helper.py, linkedin/tools/posts.py, linkedin/tools/users.py
The LinkedIn Tool allows users to post shares on linkedIn. 
Functions:
- Create Post. Support all 4 categories. This allows user to create a post with image/video uploaded to workspace.
-  Text
- Article/URL
- Image
- Video
- Get Current User.
Tracking issue: https://github.com/obot-platform/obot/issues/1326
=> feat: Linkedin Tool

generic-openai-model-provider/go.mod, generic-openai-model-provider/go.sum, generic-openai-model-provider/main.go, generic-openai-model-provider/tool.gpt, index.yaml
Based on https://github.com/obot-platform/tools/pull/375
=> feat: add generic-openai-model-provider

auth-providers-common/pkg/state/state.go, github-auth-provider/main.go, google-auth-provider/main.go
This goes along with https://github.com/obot-platform/obot/pull/1561
=> fix: auth provider cookie names

anthropic-model-provider/tool.gpt, deepseek-model-provider/tool.gpt, generic-openai-model-provider/tool.gpt, github-auth-provider/tool.gpt, google-auth-provider/tool.gpt, groq-model-provider/tool.gpt, ollama-model-provider/tool.gpt, openai-model-provider/tool.gpt, vllm-model-provider/tool.gpt, voyage-model-provider/tool.gpt, xai-model-provider/tool.gpt
Obot: https://github.com/obot-platform/obot/pull/1538
=> chore: switch model-/auth-providers to new metadata logic

outlook/calendar/credential/tool.gpt, outlook/mail/credential/tool.gpt
=> Fix: Correct json for outlook

generic-credential/main.go
to address https://github.com/obot-platform/obot/issues/1649
=> change generic credential button text

github-auth-provider/main.go, google-auth-provider/main.go
=> chore: auth providers: disable logging

vllm-model-provider/tool.gpt
issue https://github.com/obot-platform/obot/issues/1104
=> fix: vllm providerMeta missing comma

excel/credential/tool.gpt, word/credential/tool.gpt
This PR fixes typo for incorrect scope.
=> Fix: fix typo for incorrect scope

auth-providers-common/pkg/state/state.go, github-auth-provider/main.go, github-auth-provider/tool.gpt, google-auth-provider/main.go, google-auth-provider/tool.gpt
for https://github.com/obot-platform/obot/issues/1573
=> enhance: auth providers: make cookie refresh duration configurable

wordpress/main.py, wordpress/requirements.txt, wordpress/tool.gpt, wordpress/tools/helper.py, wordpress/tools/media.py, wordpress/tools/posts.py
To address https://github.com/obot-platform/obot/issues/1682
- add tools to CRUD media files in the workspace, including image/video/audio, etc.
- other minor prompt fixes.
=> enhance: support media posts for wordpress tools

auth-providers-common/templates/error.html
Addresses https://github.com/obot-platform/obot/issues/1557
Requires obot PR: https://github.com/obot-platform/obot/pull/1777
=> fix: use preAuthRedirect to properly redirect

search/tavily/main.py
Enables better parsing in the UI
Signed-off-by: Ryan Hopper-Lowe <ryan@acorn.io>
=> fix: convert tavily search response to valid json

index.yaml, pagerduty/credential/tool.gpt, pagerduty/index.js, pagerduty/package-lock.json, pagerduty/package.json, pagerduty/src/incidents.js, pagerduty/src/users.js, pagerduty/tool.gpt
Allows setting up either API key or OAuth flows.
=> enhance: add PagerDuty tool.

wordpress/main.py, wordpress/tool.gpt, wordpress/tools/categories.py, wordpress/tools/media.py, wordpress/tools/posts.py, wordpress/tools/tags.py
https://github.com/obot-platform/obot/issues/1847
This PR:
- Add capabilities to CRUD wordpress categories and tags
- support posts to get created/updated with categories and tags.
- support listing posts with categories and tags as filters.
=> enhancement: WordPress Tool - Support Categories and Tags 

postgres/credential/tool.gpt, postgres/main.go
=> chore: postgres: use connection string instead of separate fields

postgres/credential/tool.gpt
This usually contains a password.
=> chore: postgres: mark connection string as sensitive

slack/index.js, slack/src/tools.js, slack/tool.gpt
for https://github.com/obot-platform/obot/issues/1768
=> fix: slack: allow LLM to search for messages sorted by time

google/gmail/currentEmail.py, google/gmail/tool.gpt
This will be needed for https://github.com/obot-platform/obot/issues/1921
=> enhance: gmail: add tool to get the signed in user's address

word/pkg/commands/list.go, word/pkg/graph/docs.go
for https://github.com/obot-platform/obot/issues/2136
=> fix: word: fix file listing

index.yaml, outlook/mail/main.go, outlook/mail/pkg/commands/getMyEmaillAddress.go, outlook/mail/pkg/graph/mail.go, outlook/mail/tool.gpt
Add ability to send email to the signed in user itself.
The new method matches what we have for gmail.
https://www.loom.com/share/1789439398614e3cb8d6b3653b8499e2
=> Chore: add ability to get user's current email address

google/gmail/getAttachment.py, google/gmail/listAttachments.py, google/gmail/requirements.txt, google/gmail/tool.gpt, knowledge/pkg/cmd/load.go
This PR adds ability to read attachment file from gmail. It also use knowledge tools to load different types of file and feed it directly into context.
https://github.com/obot-platform/obot/issues/2209
=> Enhance: Add ability to read attachments from gmail

github/index.js, github/src/tools.js, github/tool.gpt
List authenticated users repos
List authenticated users org repos
List a users public repos
List an orgs public repos
=> enhance: cover the list repository scenarios

outlook/mail/main.go, outlook/mail/pkg/commands/createDraft.go, outlook/mail/pkg/graph/mail.go, outlook/mail/tool.gpt
Add abilities to create a draft message to reply to an email.
https://github.com/obot-platform/obot/issues/2251
=> Enhance: Add ability to create an draft to reply to a message

slack/tool.gpt
Make sure slack can format message correctly before sending it.
=> Enhance: make sure slack to correctly format message

google/gmail/sendEmail.py, google/gmail/tool.gpt, google/gmail/updateDraft.py
Fixed an regression bug where user can't send gmail. Also fixed an issue where you can't update draft.
=> Fix: fix gmail to be able to send message and update draft

google/calendar/tools/event.py
quick fix for update_event tool
=> fix: fix update_event for google calendar tool

zoom/tool.gpt, zoom/tools/meetings.py, zoom/tools/recordings.py
Bug fixes based on @sejubar 's feedback:
- trim white-spaces in meetingID and UUID.
- Rename the two tools to reflect that they are related to cloud recordings.
- enhance prompt to let agent potentially integrates with google/outlook calendar once a meeting got scheduled.
=> fix:  Zoom Tool bug fix

slack/tool-bot.gpt
Add format message tool to slack bot tool.
=> Fix: add format message tool to slack bot tool

google/gmail/helpers.py
Getting the user timezone info using the python SDK was failing because
the client was configured to use the Gmail API instead of the Calendar
API. This was causing the query to fail and default to UTC. Since we
can't update scopes on the credential gmail is using to add Google Calendar
access while our OAuth app is under review by google, switch to using
the timezone Obot is injecting into the tool for formatting `before` and
`after` queries.
Addresses https://github.com/obot-platform/obot/issues/518
=> fix: use obot user timezone to format gmail before and after queries

oauth2/main.go
Part of https://github.com/obot-platform/obot/issues/2369
=> enhance: update message for auth method selection prompt

gitlab/credential/tool.gpt, gitlab/main.go, gitlab/pkg/commands/utilities.go, gitlab/tool.gpt
Works with oauth and base urls
=> enhance: add oauth and custom url support

index.yaml, proxycurl/credential/tool.gpt, proxycurl/main.py, proxycurl/requirements.txt, proxycurl/tool.gpt, proxycurl/tools/api.py, proxycurl/tools/helper.py, proxycurl/tools/profile.py, proxycurl/tools/search.py
- Fetches Linkedin profiles of company, school, or user given URL.
- Searches for company and user profiles, as well as job listings, based on search criteria.
=> feat: create proxycurl tool

slack/credential/bot.gpt, slack/index.js, slack/package-lock.json, slack/package.json, slack/src/tools.js, slack/tool-bot.gpt, slack/tool.gpt
Add ability to set typing status in our slack app to make it fun.
=> Enhance: Add abilities to set typing status in slack

github/index.js
for https://github.com/obot-platform/obot/issues/2367
Octokit was logging some unnecessary information.
=> fix: github: disable logging

excel/pkg/graph/worksheet.go
for https://github.com/obot-platform/obot/issues/2320
I guess for some reason the old way we were doing it didn't always work with personal Microsoft accounts. I had a personal account that wasn't working with the old code, but does work with these changes.
=> fix: excel: fix listing workbooks for personal accounts

database/tool.gpt
Addresses https://github.com/obot-platform/obot/issues/2090
=> chore: remove capability category from database tools

bluesky/src/tools.ts, discord/package.json, discord/src/index.ts, generic-credential/main.go, github/index.js, oauth2/main.go, postgres/main.go, wordpress/main.py, wordpress/tools/helper.py, wordpress/tools/users.py
Thanks to @StrongMonkey for the design here. This introduces a change to allow us to bubble a structured error all the way back up to obot for credentials with a `validationTool` set.
for https://github.com/obot-platform/obot/issues/2367
=> enhance: improve error messages for credential validation tools

images/tool.gpt
for https://github.com/obot-platform/obot/issues/2546
=> fix: update prompt of generate image tool for gpt4.1

outlook/mail/pkg/graph/mail.go, outlook/mail/tool.gpt
https://github.com/obot-platform/obot/issues/2582
when folder_id not provided, list messages from all folders
=> fix: when folder_id not provided, list messages from all folders

database/tool.gpt, memory/tool.gpt
Make memory and database capabilities.
Related to:
- https://github.com/obot-platform/obot/issues/2603
- https://github.com/obot-platform/obot/issues/2090
=> chore: make memory a capability tool

memory/go.mod, memory/go.sum, memory/main.go, memory/tool.gpt
- Bump `apiclient` module to get updated memory client methods and types
- Add tools to update and delete memories
- Rename `Add Memory` tool to `Create Memory`
Addresses part of https://github.com/obot-platform/obot/issues/2612
Depends on https://github.com/obot-platform/obot/pull/2666
=> enhance: add delete and update memory tools

outlook/mail/main.go, outlook/mail/pkg/commands/downloadAttachment.go, outlook/mail/pkg/commands/getAttachment.go, outlook/mail/pkg/commands/getGroupThreadMessageAttachment.go, outlook/mail/pkg/commands/listGroupThreadMessageAttachments.go, outlook/mail/pkg/graph/attachments.go, outlook/mail/pkg/graph/group.go, outlook/mail/pkg/graph/mail.go, outlook/mail/tool.gpt
for https://github.com/obot-platform/obot/issues/2647
=> enhance: outlook mail: add tools for attachments

wordpress/tools/posts.py
quick fix for https://github.com/obot-platform/obot/issues/2674
=> quick fix: Notify the user that a deleted published post may still appear temporarily in their browser due to caching

images/package-lock.json, images/package.json, images/src/generate.ts
Addresses https://github.com/obot-platform/obot/issues/2704
Signed-off-by: Nick Hale <4175918+njhale@users.noreply.github.com>
=> fix: update generate image buffer handling for node 22

google/gmail/apis/helpers.py, google/gmail/apis/labels.py, google/gmail/apis/messages.py, google/gmail/commands/modify_message_labels.py, google/gmail/tool.gpt
- check if label is "" -- to address https://github.com/obot-platform/obot/issues/2727
- allow apply labels update actions to threads for https://github.com/obot-platform/obot/issues/2591#issuecomment-2830543594
=> fix: Gmail bug archive

microsoft365/outlook/calendar/pkg/recurrence/recurrence.go, microsoft365/outlook/calendar/tool.gpt
Credit goes to dopest donnie for finding out the fix. 
https://github.com/obot-platform/obot/issues/2637
=> Fix: use model credential and set proper options in sdk

microsoft365/outlook/calendar/main.go, microsoft365/outlook/calendar/pkg/commands/getEventAttachments.go, microsoft365/outlook/calendar/pkg/commands/listEvents.go, microsoft365/outlook/calendar/pkg/commands/modifyEventAttendees.go, microsoft365/outlook/calendar/pkg/commands/searchEvents.go, microsoft365/outlook/calendar/pkg/graph/calendar.go, microsoft365/outlook/calendar/pkg/graph/events.go, microsoft365/outlook/calendar/pkg/graph/groups.go, microsoft365/outlook/calendar/tool.gpt
- Support set required/optional attendees for Create Event Tool for https://github.com/obot-platform/obot/issues/2640
- Rework InviteUserToEvent to ModifyEventAttendees Tool to support required/optional attendees: https://github.com/obot-platform/obot/issues/2745
=> fix: Outlook calendar required/optional attendees

microsoft365/outlook/mail/main.go, microsoft365/outlook/mail/pkg/commands/getEmailDetails.go, microsoft365/outlook/mail/pkg/graph/group.go, microsoft365/outlook/mail/tool.gpt
https://github.com/obot-platform/obot/issues/2754
To get email details of group mails
=> fix: Outlook mail get groupmail detail

search/tavily/main.py, search/tavily/obot-search.gpt, search/tavily/tool.gpt
for https://github.com/obot-platform/obot/issues/2600
I hate marring such a beautifully simple, single-parameter tool by adding a second param, but there isn't another way that I know of to fix the issue I linked above.
=> fix: tavily/obot search: add time_range parameter

google/search/src/search.ts
The timeout seems to be too low for loading a page. Some page needs to render js to get the full body. Increasing the timeout fixed the issue. https://github.com/obot-platform/obot/issues/2749
=> Fix: increase the timeout when loading page

images/src/analyze.ts
I believe this is the smallest pull request I have ever submitted.
for https://github.com/obot-platform/obot/issues/2677
=> fix: images: fix reading undefined array

openai-model-provider/openaiproxy/proxy.go, openai-model-provider/proxy/rewrite.go
this will take care of https://github.com/obot-platform/obot/issues/2862#event-17618706700
Also added o3 and o4 series models to chat models, removed o1-mini/o1-preview/o1-pro
=> fix: detect OAI reasoning models, and have their temperatures fixed to 1.0

anthropic-model-provider-go/proxy/proxy.go
https://github.com/obot-platform/obot/issues/2936
`Arguments` cannot be omitted for Anthropic models
=> fix: anthropic models fix when tool call with no args

microsoft365/outlook/mail/tool.gpt
for https://github.com/obot-platform/obot/issues/2762
=> fix: outlook mail: tell LLM when to look up group information

microsoft365/onedrive/pkg/commands/addPermission.go, microsoft365/onedrive/tool.gpt
https://github.com/obot-platform/obot/issues/2863
simply removed invalid roles
=> quickfix: remove invalid roles

google/docs/update_doc.py
https://github.com/obot-platform/obot/issues/2825
quick one line fix
=> fix: local variable

discord/tool.gpt, github/tool.gpt, gitlab/tool.gpt, google/calendar/tool.gpt, google/docs/tool.gpt, google/drive/tool.gpt, google/gmail/tool.gpt, google/sheets/tool.gpt, microsoft365/excel/tool.gpt, microsoft365/onedrive/tool.gpt, microsoft365/outlook/calendar/tool.gpt, microsoft365/outlook/mail/tool.gpt, microsoft365/word/tool.gpt, notion/context.gpt, notion/tool.gpt, pagerduty/tool.gpt, slack/tool-bot.gpt, slack/tool.gpt, smartthings/tool.gpt, wordpress-seo/tool.gpt, wordpress/tool.gpt
=> Chore: Switch to xml tags for instructions

atlassian/jira/tool.gpt, database/pkg/cmd/context.go, firecrawl/tool.gpt, images/tool.gpt, memory/tool.gpt, sendgrid/tool.gpt, shell/tool.gpt, smartthings/tool.gpt
Getting the ones I missed on the first pass.
=> Chore: Update instructions to xml tags

microsoft365/word/pkg/commands/list.go, microsoft365/word/pkg/graph/docs.go
for https://github.com/obot-platform/obot/issues/2662
=> fix: attach parentFolder Path to Doc to avoid conflict (same) doc names

microsoft365/outlook/mail/main.go, microsoft365/outlook/mail/pkg/client/client.go, microsoft365/outlook/mail/pkg/commands/createDraft.go, microsoft365/outlook/mail/pkg/commands/deleteGroupThread.go, microsoft365/outlook/mail/pkg/commands/listEmails.go, microsoft365/outlook/mail/pkg/commands/listGroupThreads.go, microsoft365/outlook/mail/pkg/commands/listMailFolders.go, microsoft365/outlook/mail/pkg/commands/searchEmails.go, microsoft365/outlook/mail/pkg/graph/folders.go, microsoft365/outlook/mail/pkg/graph/group.go, microsoft365/outlook/mail/pkg/graph/mail.go, microsoft365/outlook/mail/pkg/printers/mail.go, microsoft365/outlook/mail/tool.gpt
https://github.com/obot-platform/obot/issues/2718
=> fix: support read/unread status when listing emails

workspace-files/main.go, workspace-files/tool.gpt
Addresses part of https://github.com/obot-platform/obot/issues/3212
Depends on https://github.com/obot-platform/obot/pull/3231
=> enhance: expose project files to the workspace-files tool

openai-model-provider/openaiproxy/proxy.go
This is to ensure that the temperature and roles get set properly.
=> chore: add gpt-5 as a reasoning model

index.yaml
remove sheets from index.yaml to fix the test
=> cleanup index.yaml

google/gmail/obot_gmail_mcp/apis/helpers.py, google/gmail/obot_gmail_mcp/apis/messages.py, google/gmail/obot_gmail_mcp/server.py, google/gmail/pyproject.toml, google/gmail/tests/test_server.py, google/gmail/uv.lock
- improve descriptions
- handle string input for bool type args (`"true" instead of True`)  -- cursor has a bug right now.
=> chore: fix gmail list email tool description

groq-model-provider/tool.gpt
Depends on https://github.com/obot-platform/obot/pull/3890
=> chore: use groq logo from ui assets

images/package.json, images/src/analyze.ts, images/src/generate.ts, images/src/tools.ts, images/tool.gpt
Address https://github.com/obot-platform/obot/issues/3883
=> Fix: reinforce prompt to give array input

github-auth-provider/main.go
The idea here is to provide another endpoint that Obot can use to periodically query for the auth groups a user belongs to, instead of querying for the groups every time `/obot-get-state` is called.
Addresses part of https://github.com/obot-platform/obot/issues/3484
=> enhance: add endpoint to list github user auth groups

google/drive/app/apis/files.py, google/drive/app/apis/helper.py, google/drive/app/apis/permissions.py, google/drive/app/apis/shared_drives.py, google/drive/app/server.py, google/drive/pyproject.toml, google/drive/tests/test_server.py, google/drive/uv.lock
- https://github.com/obot-platform/obot/issues/3919#event-19325906776 add ability to read a google drive file
- https://github.com/obot-platform/obot/issues/3886#event-19325649332 handle tool exceptions correctly
=> Google Drive MCP tools fixes

github-auth-provider/tool.gpt, google-auth-provider/tool.gpt
Address [#4246](https://github.com/obot-platform/obot/issues/4246)
=> Update the helper text to reflect the latest UI updates
