obot-platform/tools

apis/notion/code/.gitignore, apis/notion/code/README.md, apis/notion/code/index.js, apis/notion/code/package-lock.json, apis/notion/code/package.json, apis/notion/code/src/database.js, apis/notion/code/src/pages.js, apis/notion/code/src/search.js, apis/notion/code/tool.gpt, apis/notion/read/tool.gpt, apis/notion/write/tool.gpt, apis/slack/code/.gitignore, apis/slack/code/README.md, apis/slack/code/index.js, apis/slack/code/package-lock.json, apis/slack/code/package.json, apis/slack/code/src/tools.js, apis/slack/code/tool.gpt, apis/slack/read/tool.gpt, apis/slack/write/tool.gpt
This PR adds tool sets for Slack and Notion, split into separate read and write tools. These are both code-based and use each service's SDK, since they don't have (up-to-date) OpenAPI files. Both the read and write tools share the same code tool, so I set up the directories like `apis/{slack,notion}/{read,write,code}`, and made the read and write tools reference the code tool. I think this structure makes sense, but let me know if you have a better idea.
=> add slack and notion tools

clis/aws/tool.gpt
Without this chatgpt was not properly quoting the command arguments for aws cli, this resulted in wrong commands, when ' or " were part of the command argument. 
I discovered this issue when playing around with aws athena.
=> Quote command arguments in aws cli

apis/outlook/mail/manage/tool.gpt, apis/outlook/mail/read/tool.gpt
Just a little prompting tweak.
=> fix: outlook mail: encourage the LLM to include the body preview in output

apis/slack/code/index.js, apis/slack/code/src/tools.js, apis/slack/code/tool.gpt, apis/slack/read/tool.gpt
This PR:
- adds a `get_channel_history_by_time` tool that lets you set start and end time parameters
- prints errors to stdout instead of stderr
- improves output of messages by including more information
- encourages the LLM to set a limit of 10 by default when querying for channel history, to avoid taking too much time
=> more Slack improvements

apis/outlook/mail/code/main.go, apis/outlook/mail/code/pkg/commands/searchMessages.go, apis/outlook/mail/code/pkg/graph/mail.go, apis/outlook/mail/code/pkg/util/util.go, apis/outlook/mail/code/tool.gpt
for gptscript-ai/desktop#199
This PR improves the experience searching for emails. Rather than using a generic search query that often returns irrelevant results, we now allow the LLM to search specifically by subject, sender email address, and/or sender full name. This should produce much more relevant search results.
=> fix: improve outlook mail search

apis/github/code/index.js, apis/github/code/src/tools.js, apis/github/code/tool.gpt, apis/github/read/tool.gpt
Issue search can be used to list issues and PRs with better results than
the basic list commands. One of the core problems is that these list
commands only return open issues and PRs. Remove them in favor of
relying on issue search.
=> enhance: remove list issues and prs commands

apis/excel/read/tool.gpt, apis/excel/write/tool.gpt
Just noticed this today. These tool sets are supposed to share the tools, which they weren't doing.
=> fix: excel: share the tools

apis/outlook/calendar/code/tool.gpt, apis/outlook/calendar/manage/tool.gpt, apis/outlook/calendar/read/tool.gpt, apis/outlook/mail/code/tool.gpt, apis/outlook/mail/manage/tool.gpt, apis/outlook/mail/read/tool.gpt
As I was working on step templates, I realized it would be nice to be able to refer to individual tools from the `code` folder for each of these, which requires them to define their own credentials. We have been following this pattern for newer tools and it seems to be better than what we were doing before, so here is the PR to do this for the Outlook tools.
=> chore: outlook: define credentials on each tool

apis/github/index.js, apis/github/src/tools.js, apis/github/tool.gpt
Searching issues and PRs with the GitHub "Search Issues and PRs" tool is currently limited by the default query result count. To fix this, add pagination to the tool so the LLM can discover all results for a given query.
=> enhance: add pagination to the "Search Issues and PRs" tool

apis/excel/tool.gpt, apis/github/tool.gpt, apis/google/gmail/tool.gpt, apis/google/sheets/tool.gpt, apis/google/youtube/tool.gpt, apis/notion/tool.gpt, apis/outlook/calendar/tool.gpt, apis/outlook/mail/tool.gpt, apis/slack/tool.gpt
Add category and icon URL to tool set metadata. This will enable better tool
set search and the use of common icons across tools within each set.
Note: This doesn't include metadata for the hubspot tool. I believe that still needs to be refactored to collapse the read/write tools into a single tool. If so, I'll include the metadata in a separate refactor PR.
=> enhance: add category and icon metadata to tools

google/search/.eslintignore, google/search/.eslintrc.cjs, google/search/.gitignore, google/search/package-lock.json, google/search/package.json, google/search/src/context.ts, google/search/src/getMarkdown.ts, google/search/src/refineQuery.ts, google/search/src/search.ts, google/search/src/server.ts, google/search/tool.gpt, google/search/tsconfig.json, index.yaml
Add the `Google Search` tool.
This is a modified version of [answers-from-the-internet](https://github.com/gptscript-ai/answers-from-the-internet) that responds with knowledge-like references to relevant search result page content instead of answering questions directly.
e.g.
```json
{
"question": "what is an opossum?",
"results": [
{
"url": "https://www.merriam-webster.com/dictionary/opossum",
"title": "Merriam-Webster Dictionary - Opossum",
"relevantContent": [
"Opossum: any of a family (Didelphidae) of small- to medium-sized American marsupials that usually have a pointed snout and nearly hairless scaly prehensile tail, are typically active at night, and are sometimes hunted for their fur or meat.",
"Especially: a common omnivorous largely nocturnal mammal (Didelphis virginiana) of …
```
=> feat: add google search tool

google/search/tool.gpt
- Add Google Search tool bundle to align with established pattern
- Add an icon for Google Search
- Fix category metadata typo that was preventing the UI from discovering
the Google Search category
=> fix: google search metadata

google/search/src/refineQuery.ts, google/search/src/search.ts, google/search/src/server.ts, google/search/tool.gpt
Make Google Search query refinement more conservative by adding the `Current Date and Time` context tool to internal tool calls and tweaking the refinement tool prompt. This should help prevent the refined query changing too much and negatively impacting the results, especially when the query involves dates.
e.g. before this change "Who won the 2024 Super Bowl?" is refined to "2024 Super Bow predictions and favorites" which results in content from old articles being returned. After adding this change, the query is refined to "Who won the Super Bowl 2024" which results in content that can actually answer the question.
This change also suppresses `npm run` script body printing to ensure the tool produces valid JSON.
=> fix: make google search refinement more conservative 

knowledge/data-sources/website/colly.go
Added another check so that urls like
`[Kube API Down](https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeapidown/)` are also scraped.
This now covers the case where the link URL does contain a host entry, not just a path.
=> fix: allow scraping URLs with full domains

notion/tool.gpt
The Notion bundle wasn't showing up because of a typo in the bundle
metadata definition. Correct this by switching to the new shorthand for
defining bundle metadata.
Addresses https://github.com/otto8-ai/otto8/issues/250
=> fix: notion bundle metadata

google/search/package-lock.json, google/search/package.json, google/search/src/context.ts
Don't rely on post-install script to install chromium for google search.
Instead, use whatever browser has already been installed on the system.
Supports Chrome, Chromium, Firefox, and Edge.
=> enhance: use system browser for google search

knowledge/data-sources/onedrive/main.go, knowledge/data-sources/website/colly.go, knowledge/data-sources/website/main.go
1. Fix onedrive so that when error is written in metadata, don't exit with 1 so that error can be propagated back.
2. Fix website to show logs from thread.
https://github.com/otto8-ai/otto8/issues/230
=> Fix: make website tool output to stdout, handle error gracefully

outlook/mail/tool.gpt
Add a line to the context for Outlook Mail Tools that prevents the LLM from attempting to forward emails. This will be added as a standalone tool.
Addresses https://github.com/otto8-ai/otto8/issues/102
=> fix: prevent outlook mail forwarding

google/gmail/tool.gpt
Shore up the Gmail tools to prevent them from using drafts to reply to or forward emails until first-class support for these operations is implemented.
Addresses: https://github.com/otto8-ai/otto8/issues/99
=> fix: prevent gmail reply and fwd via drafts

outlook/calendar/credential/tool.gpt, outlook/calendar/main.go, outlook/calendar/pkg/commands/getDefaultTimezone.go, outlook/calendar/pkg/global/global.go, outlook/calendar/tool.gpt
Add the `Get Default Timezone` tool to `Outlook Calendar` to avoid prompting
the user for a timezone to use when creating or modifying events.
The tool returns the timezone from their Outlook mailbox settings.
Addresses: https://github.com/otto8-ai/otto8/issues/169
~Note: Some permissions need to be approved [here](https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/CallAnAPI/appId/b89e586d-26d5-4126-8012-dbad9c137417/defaultBlade/CallAnAPI) before I can test this (even though that page seems to say otherwise, the challenge page is still blocking me on admin approval for app permissions cc @drpebcak)~
=> enhance: add default timezone tool to outlook calendar

slack/package-lock.json, slack/package.json, slack/src/tools.js
This updates the Slack tool to use the newest version of node-gptscript, which is needed to get datasets working again with Otto.
=> chore: bump node-gptscript for Slack

google/gmail/helpers.py, outlook/mail/pkg/commands/listMessages.go
At the moment, datasets do not preserve the order of elements anymore, which I need to fix. For now, let's just skip them in places where the order might matter, which I think is these three tools.
=> chore: skip datasets in areas where we need ordered elements

outlook/calendar/main.go, outlook/calendar/pkg/graph/events.go, outlook/calendar/pkg/recurrence/doc.md, outlook/calendar/pkg/recurrence/recurrence.go, outlook/calendar/pkg/recurrence/recurrence_test.go, outlook/calendar/tool.gpt
Recurring meetings in the Outlook Calendar API are fairly complicated. To help handle this, I implemented an internal tool call to turn a plain English description of the recurrence logic into the proper fields required by the API. I have tested this thoroughly and it works well.
=> enhance: outlook calendar: support the creation of recurring meetings

browser/.eslintignore, browser/.eslintrc.cjs, browser/.gitignore, browser/package-lock.json, browser/package.json, browser/src/browse.ts, browser/src/context.ts, browser/src/delay.ts, browser/src/enter.ts, browser/src/fill.ts, browser/src/scrollToBottom.ts, browser/src/select.ts, browser/src/server.ts, browser/src/session.ts, browser/tool.gpt, browser/tsconfig.json, index.yaml
Add MVP `Browser` tools with updated session management for use in Otto.
This means:
- The `Browser` tool daemon doesn't store session data in the workspace directory
-- which is now deleted after each tool call -- and instead creates an independent session directory and browser process for each unique workspace ID it encounters 
- The session directories and browser processes are still ephemeral, but now have a 10 minute TTL from last use
- Workspace IDs are taken from the headers of requests to the tool daemon (can't use the environment variable anymore because tool daemons are effectively singletons in Otto)
=> feat: add browser tools

slack/package-lock.json, slack/package.json, slack/src/tools.js
Cache user names to speed up requests to get channel history from slack.
=> fix: speed up slack requests by caching user names

knowledge/go.mod, knowledge/pkg/datastore/documentloader/mupdf.go, knowledge/pkg/datastore/documentloader/pdf/mupdf/pdf.go
Command + Logs
```bash
$ knowledge load --loader=mupdf .local/testdata/files/2023q4-alphabet-earnings-release.pdf -
2024/10/30 16:25:06 DEBUG Merged PDF pages totalPages=11 mergedPages=4
```
Output/Results:
```json
{
"metadata": {
"source": ".local/testdata/files/2023q4-alphabet-earnings-release.pdf",
"totalPages": 11
},
"documents": [
{
"metadata": {
"pages": "1-2",
"tokenCount": 1107
},
"content": "Alphabet Announces Fourth Quarter and Fiscal Year 2023 Results\n\nMOUNTAIN VIEW, Calif. – January 30, 2024 – Alphabet Inc. (NASDAQ: GOOG, GOOGL) today announced\n\nfinancial results for the quarter and fiscal year ended December 31, 2023.\n\nSundar Pichai, CEO, said: “We are pleased with the ongoing strength in Search and the growing contribution from\n\nYouTube and Cloud. Each of these is …
```
=> feat: (knowledge) mupdf merge pages by default within tokenlimit

knowledge/pkg/cmd/load.go
e.g. if it's an image-only PDF and was parsed with mupdf which doesn't read anything from it
=> fix: (knowledge) return error (instead of panic) if not documents were parsed from a file

knowledge/pkg/datastore/documentloader/ocr/openai/openai.go, knowledge/pkg/datastore/documentloader/pdf/gopdf/pdf.go, knowledge/pkg/datastore/documentloader/pdf/mupdf/pdf.go, knowledge/pkg/datastore/documentloader/structured/structured.go, knowledge/pkg/datastore/ingest.go, knowledge/pkg/datastore/textsplitter/adapter.go, knowledge/pkg/datastore/textsplitter/defaults.go, knowledge/pkg/datastore/textsplitter/textsplitter.go, knowledge/pkg/datastore/types/types.go, knowledge/pkg/flows/flows.go, knowledge/pkg/index/models.go, knowledge/pkg/vectorstore/types/types.go
Adds:
- `docIndex` and `docsTotal` metadata keys (stored in VectorDB)
- `index` column in `documents` table
Fixes:
- PDF documents being re-chunked by textsplitter because chunkOverlap was not considered
=> feat: (knowledge) add document index (location in file) to db

outlook/calendar/pkg/commands/searchEvents.go
=> chore: outlook calendar: make search case insensitive

outlook/calendar/pkg/graph/events.go
Apparently I just forgot to add this line when I first wrote this tool.
=> fix: outlook calendar: createEvent: set event body

notion/src/search.js
This fixes a couple of issues in the Notion search tool:
1. Names were always showing up as `undefined` because I was reading them from the wrong place on the result object.
2. The elements said that every result was a page, even if it was actually a database. We now distinguish between the two.
=> fix: notion: use the right name/type in search results

slack/index.js, slack/tool.gpt
I'm not sure how the code got removed from the tool block in the GPT file, or how I was somehow missing a parameter in the function call, but this fixes both of those problems.
=> fix: slack: fix sending messages in threads

notion/tool.gpt
Add context to the Notion tools to confirm with the user before creating new pages. This will prevent pages from being created when the user is actually attempting to update the content of an existing page.
This change also bumps node-gptscript to include the new dataset changes.
Addresses https://github.com/otto8-ai/otto8/issues/251
=> fix: add context to prevent notion from creating unwanted pages

knowledge/pkg/cmd/load.go
- this only affects `knowledge load`
=> change: knowledge - print `{"unsupportedFiletype": "xyz"}` instead of `{"error": "xyz"}` on `load`

notion/src/search.js
We were sometimes getting an error from how we were trying to read the database title in the `resultToString` function. Since we find the name before we call this function, I figured we might as well just pass it in instead of looking for it again.
=> fix: notion: read the page name from the right place

outlook/mail/main.go, outlook/mail/pkg/commands/searchMessages.go, outlook/mail/pkg/graph/mail.go, outlook/mail/tool.gpt
This adds new `start` and `end` params as bounds for the Search Messages tool, and also now provides search results in reverse chronological (most recent first) order.
=> enhance: outlook mail: search messages: sort reverse chrono and add start/end params

slack/index.js, slack/src/tools.js, slack/tool.gpt
This provides additional context for the Slack tools about who the signed in user is, including their default time zone, so when they ask for things like "list all messages from today in the general channel", the LLM will know what time zone to use.
=> enhance: slack: add user context

images/src/generate.ts, images/tool.gpt
Return file paths from the Generate Image tool that can be accessed by the Otto8 UI and share a new context tool to prevent LLMs from tacking on a HTTPS protocol prefix (`gpt-4o` couldn't resist...)
**Before**: `files/<image>.png`
**After**:  `/api/threads/<thread_id>/file/<image>.png`
Additionally, change the convention for generated file names to make their origin more clear.
**Before**: `550d3ea4c5d64d727486f62da2d1d0ed5b0e59246d8e922a92b48c5a9e37f3a5.png`
**After**:  `generated_image_550d3ea4.png`
=> enhance: generate image paths accessible to the otto8 ui

images/tool.gpt
Change the `Images Context` to stop the LLM from altering the file paths
returned by the `Generate Images` in its markdown responses.
=> fix: generated image path usage

images/src/analyze.ts, images/src/generate.ts, images/src/tools.ts, images/tool.gpt
Add support for analyzing image files from the workspace. This enables users to analyze images generated by `Generate Images` in addition to files they've directly uploaded to the workspace.
Addresses: https://github.com/otto8-ai/otto8/issues/431
=> enhance: analyze image workspace file support

google/search/src/refine.ts, google/search/src/search.ts
Speed up Google Search by:
- preferring extracting search result page main content when it's available
- skipping internal tool calls for result content 10k "tokens" (characters) or less
=> enhance: prefer main content in google search

index.yaml
Google blocks transcript requests from certain public cloud IPs,
which breaks the `YouTube Transcriber` tool when it's running from
our test and demo instances in Render.
A workaround won't be ready in time for Kubecon, so this change
removes it from the index for now.
See https://acorn-io.slack.com/archives/C03FU91U4SX/p1731181637315179
for details.
=> chore: temporarily de-index youtube transcriber

google/search/src/refine.ts, google/search/src/server.ts, google/search/tool.gpt, images/src/analyze.ts, images/src/generate.ts, images/src/tools.ts, images/tool.gpt
Remove `Model` tool parameters. The models used by these tools shouldn't change.
=> chore: remove model params from google search and images tools

browser/src/screenshot.ts, browser/src/server.ts, browser/src/session.ts, browser/tool.gpt
Fix browser screenshot rendering by returning well-structured JSON containing screenshot `downloadUrl` fields and other info.
Bonus features:
- Add a `fullPage` parameter to the `Screenshot` tool to enable full page screenshots.
- Add a `followMode` field and some context to the Browser tools that allows users to get and display a screenshot of the browser page at the end of each successful tool call by asking the assistant to "enable follow mode"
Addresses https://github.com/otto8-ai/otto8/issues/497 for the browser tool.
=> fix: browser screenshot rendering

knowledge/data-sources/website/colly.go, knowledge/data-sources/website/colly_test.go
Properly fix the relative path scraping when user input a subPath. The relative path from href should work if joined with the current url is the subpath of the baseURl.
edit:
Also added ability to detect linkUrl if it is a variant of baseURl. For example, www*.foo.com will be allowed if baseURl is foo.com. Vice verse.
=> Fix: properly handle relative path when user put a subpath

knowledge/data-sources/website/colly.go
When comparing linkurl with baseURl, we should always add "/" after the path. This is so that `www.acorn.io/docs` doesn't get dropped when resolving link reference to `index.yaml`. Without "/" it will intepret as `www.acorn.io/index.yaml` instead of `www.acorn.io/docs/index.yaml`
https://github.com/otto8-ai/otto8/issues/595#event-15306143444
=> Fix: make sure slash is appended after baseUrl path

knowledge/pkg/datastore/defaults/defaults.go, knowledge/pkg/datastore/documentloader/ocr/openai/openai.go, knowledge/pkg/datastore/embeddings/openai/openai.go
`KNOW_MODEL_API_TIMEOUT_SECONDS` - 300s (set on context)
`KNOW_MODEL_API_REQUEST_TIMEOUT_SECONDS` - 120s (set on http client - long time sometimes required for VLM calls)
... can be overridden for embeddings and for "OCR"/VLM calls
=> chore: more generous OpenAI API timeouts for expensive requests + per-request timeouts

outlook/mail/main.go, outlook/mail/pkg/commands/listMessages.go, outlook/mail/pkg/graph/mail.go, outlook/mail/tool.gpt
Add optional `start`, `end`, and `limit` parameters to the `Outlook
Mail` bundle's `List Messages` tool. This enables listing emails by date
and supports prompts like "List the latest ${N} emails on ${DATE}".
Addresses https://github.com/otto8-ai/otto8/issues/384
=> enhance: enable listing outlook messages by time

notion/tool.gpt
Tweak the `Notion` bundle context to prevent pages from being created
automatically when a user asks to "update" or "add to" a given page.
The context instructs Agents to ask the user to confirm before it calls `Create Page` when the user hasn't explicitly asked for a page to be created.
The current context is just ambiguous enough for agents to interpret a single
confirmation of "create a new page with the updated content" as
confirmation for all subsequent prompts. This change has prevented that
in my testing.
> **Note:** IMO we should implement a true `Update Page` tool page as soon as we have the time.
Addresses https://github.com/otto8-ai/otto8/issues/251
=> fix: tweak notion context to prevent page creation when asked to update

bluesky/.eslintignore, bluesky/.eslintrc.cjs, bluesky/.gitignore, bluesky/package-lock.json, bluesky/package.json, bluesky/src/posts.ts, bluesky/src/tools.ts, bluesky/src/users.ts, bluesky/tool.gpt, bluesky/tsconfig.json, index.yaml
Add Bluesky tools with support for basic search via unauthenticated requests.
Support for authenticated requests will require a custom OAuth provider that can handle [ATProto's authz requirements](https://atproto.com/specs/oauth#clients).
Support for datasets will be implemented as a follow up.
Depends on https://github.com/otto8-ai/otto8/pull/629
=> feat: add mvp bluesky tools

google/gmail/createDraft.py, google/gmail/helpers.py, google/gmail/requirements.txt, google/gmail/sendEmail.py, google/gmail/tool.gpt
Add an optional `attachments` parameter to the `Gmail` bundle's `Create Draft` and `Send Email` tools to enable attaching workspace files when creating drafts and sending emails.
Addresses https://github.com/otto8-ai/otto8/issues/115 for the `Gmail` tool bundle
=> enhance: enable attaching workspace files when creating gmail drafts and sending emails

knowledge/data-sources/notion/.prettierrc, knowledge/data-sources/notion/src/index.ts, knowledge/data-sources/onedrive/main.go, knowledge/data-sources/website/colly.go, knowledge/data-sources/website/main.go
1. Rewrite notion sync tool to be more effifient.
2. Limit onedrive file to be < 50mb.
3. Use filepath as key in website scraper.
https://github.com/otto8-ai/otto8/issues/642
https://github.com/otto8-ai/otto8/issues/625
https://github.com/otto8-ai/otto8/issues/637
=> Fix filepath

bluesky/credential/tool.gpt, bluesky/src/posts.ts, bluesky/src/tools.ts, bluesky/tool.gpt
The `Bluesky` bundle's `Search Post` tool fails to search for posts when the `since` or `until` parameters are set due an error returned by the public bsky search APIs. This isn't well documented, but after some testing it was determined that this only occurs when making
unauthenticated requests.
To fix this issue, this change updates the Bluesky tools to make authenticated requests with a user handle and [App Password](https://bsky.app/settings/app-passwords) provided by the user via a basic auth credential tool.
This change also exposes a `tags` parameter on the `Search Post` tool to make it easier for agents to search by tag.
**Note: This PR depends on #228**
=> fix: bluesky time-bound query issues 

knowledge/data-sources/website/colly.go
Ref https://github.com/otto8-ai/otto8/issues/150
=> fix: ignore PDFs if their links lead to non-application/pdf content-types (usually redirects)

knowledge/data-sources/notion/src/index.ts
https://github.com/otto8-ai/otto8/issues/667
For any parent page that could have children, place it into the folder itself. This is to avoid parent page ending in a separate node in a tree.
=> Fix: put parent page into its own folder

knowledge/data-sources/website/colly.go, knowledge/data-sources/website/colly_test.go
https://github.com/otto8-ai/otto8/issues/675
Previously it onlys check for suffix which is not enough. It needs to check the last two parts of the url after splitted by `.`.
=> Fix: fix link url to be sub-domain

anthropic-model-provider/tool.gpt, azure-openai-model-provider/tool.gpt, model-provider-credential/tool.gpt, ollama-model-provider/tool.gpt, openai-model-provider/tool.gpt, voyage-model-provider/tool.gpt
This model provider credential exists only so that the environment variables are given to the tool when it runs. The actual credential is managed by Otto8 itself. If the credential is called, that means that the model provider has not been properly configured.
=> feat: add a fake model provider credential

knowledge/data-sources/website/colly.go
Fix so that if external pdf link belongs to the same base url folder, combine the path and remove duplicated hostname. The original intention is to place external pdf link to the base url folder with its path as the subfolder. But if the link belong to the same url, the hostname dir can be combined. 
https://github.com/otto8-ai/otto8/issues/674
=> Fix: dedup pdf path if it belongs to the base url

knowledge/pkg/datastore/embeddings/openai/openai.go
We are seeing increased timeout error when trying to make embedding requests, so this PR increases the timeout per requests. Also increase the overall context timout to be the 5x of the requests so that it can actually try 5 times. 
https://github.com/otto8-ai/otto8/issues/591
=> Fix: Increase timout to 4 minutes, increase overall timeout

.gitignore, notion/src/pages.js
This PR aims to fix issue https://github.com/otto8-ai/otto8/issues/627.
*What is fixed*:
the `CreatePage` tool now will check the length of input content, and if it's greater than the limit(2000), the tool will slice the content into smaller chunks as multiple rich_texts of the the children block of the page.
=> fix: CreatePage tool fix -- split content if it exceeds length limit 2000

workspace-files/main.go, workspace-files/tool.gpt
Add the `workspace_copy` tool to the `Workspace Files` bundle in order to support copying workspace files without exposing their content to the LLM. This allows agents to copy large and/or non-UTF8 files and enables save generated images to files with more descriptive names.
Addresses https://github.com/otto8-ai/otto8/issues/514
**Note:** ~This change has me wondering if the `workspace_read` tool should output markdown with the URL format we use for displaying images in the `Images` bundle; e.g. -> `generated_image_4663217f.png` -> `![generated_image_4663217f.png](http://main.otto8.ai/api/threads/t12v4pt/file/generated_image_4663217f.png)`. The idea is for the UI to show the image on read instead of failing.~
**Note:** I’m feeling like this is the wrong approach since having the LLM …
=> fix: support copying generated image files

google/search/src/search.ts, google/search/tool.gpt
Is a fix for https://github.com/otto8-ai/otto8/issues/856
- Add encodeURIComponent for Google search URL
- Improve URL safety for special characters and Unicode
- Prevent malformed search requests
- Change gptscript tool description to get llm to re-call the tool if it believes it needs more search results
- Change gptscript maxResults minimum value to 2 - openai gpt4o was setting this to 1 in many runs and this was preventing the run from finding the correct answer
=> fix google search tool: properly encode search query parameters

browser/src/screenshot.ts, browser/src/session.ts
This was causing the `Browser` tool daemon to fail to extract the `OBOT_THREAD_ID` and other environment variables from the `x-gptscript-env` request header and made it fall back to using the environment variable it was started with.
Addresses https://github.com/obot-platform/obot/issues/980
=> fix: trim white-space when extracting env vars from request headers

browser/package-lock.json, browser/package.json, browser/src/screenshot.ts
Update the `Browser` bunde's `Screenshot` tool to store and return webp images instead of png.
Addresses https://github.com/obot-platform/obot/issues/981
=> enhance: return webp screenshots

index.yaml, sendgrid/Makefile, sendgrid/cmd/send.go, sendgrid/credential/tool.gpt, sendgrid/go.mod, sendgrid/go.sum, sendgrid/main.go, sendgrid/tool.gpt
Depends on https://github.com/obot-platform/obot/pull/1086
Addresses https://github.com/obot-platform/obot/issues/918
=> feat: add sendgrid bundle for sending emails

tasks/tool.gpt
Since the context tool isn't using sys.echo, the prompt is fed to the LLM and the response of is being used as the context. This is not the intended behavior.
Using sys.echo here will mean that the text is used in the system prompt and the LLM is not used.
Issue: https://github.com/obot-platform/obot/issues/1066
=> fix: echo the task's context

index.yaml, sendgrid/tool.gpt
The `SendGrid` tools should not be in the `Capability` category since they don't integrate with/extend the user UI.
This change: 
- switches `SendGrid` tools to a new, dedicated, category
- switches to the official `SendGrid` icon (depends on https://github.com/obot-platform/obot/pull/1101)
- updates the context to resolve placeholders/templates in body content before sending emails
- updates the context to prefer sending an email to multiple recipients with a single `Send Email` call
=> chore: give sendgrid its own category

knowledge/data-sources/website/main.go
As we are increasing the reliability of the ingestion process, we can increase the number of the limit when scraping.
=> Chore: increase the scraping limit to 2000

bluesky/tool.gpt, browser/tool.gpt, github/tool.gpt, google/gmail/tool.gpt, google/search/tool.gpt, index.yaml, outlook/calendar/tool.gpt, outlook/mail/tool.gpt, slack/tool.gpt, time/tool.gpt
- Add the `User Timezone` context tool that exposes the user's preferred timezone provided by the `OBOT_USER_TIMEZONE` environment variable injected by Obot (depends on https://github.com/obot-platform/obot/pull/1107)
- Add a `Time` bundle that includes the `Get Current Date and Time` and `User Timezone` context tools
Addresses https://github.com/obot-platform/obot/issues/1111
=> feat: add generic user timezone context

time/tool.gpt
Update the `Current Date and Time` context tool so that it returns the user's current date and time in their local timezone instead of UTC.
=> enhance: return the user's current local time

time/tool.gpt
In some situations the `Current Date and Time` context tool is called without `OBOT_USER_TIMEZONE` environment being set by Obot, causing the call to fail with an invalid timezone error. In particular, this happens when configuring agent-scoped auth for tools
that share `Current Date and Time`, and breaks the feature.
To fix this, parse the timezone in the `Current Date and Time` and `User Timezone` tools and fall back to UTC when it's invalid.
Addresses https://github.com/obot-platform/obot/issues/1157
=> fix: fall back to utc for invalid timezones

google/search/tool.gpt
* should be "google" not "search" 🤦‍♀️ Apologies!
=> fix: correct metadata oauth for google search tool

slack/tool.gpt
- Use the new timezone context tool from the `Time` bundle to get the
user's preferred timezone
- Add a section to the `Slack Context` tool to coax the LLM into
displaying dates and times in the user's preferred timezone
Addresses https://github.com/obot-platform/obot/issues/584
Depends on https://github.com/obot-platform/tools/pull/321
=> fix: display slack messages in the users preferred timezone

sendgrid/cmd/send.go, sendgrid/credential/tool.gpt, sendgrid/main.go, sendgrid/tool.gpt
Email addresses and API keys are tightly coupled for the `SendGrid` API; i.e. you can only send emails from authorized addresses associated with the key you're using.
To codify this relationship in the `SendGrid` tool, share an additional credential to capture the email address alongside the API key.
Additionally, add an optional `from_name` parameter to the `Send Email` tool to support for setting the sender name. Default's to `Obot` if not set.
=> enhance: use credentials to capture sendgrid email address

knowledge/data-sources/onedrive/main.go, knowledge/data-sources/website/colly.go
https://github.com/obot-platform/obot/issues/1210
This also update the limit from onedrive to be consistent.
=> Chore: don't scrape any file from internet that are larger than 100 mb

database/main.go, database/pkg/cmd/context.go, database/pkg/cmd/exec.go, database/pkg/cmd/query.go, database/pkg/cmd/table.go, database/tool.gpt
To reduce confusion in both the LLM and tool maintainers, rename the following tools in the `Database` bundle:
1. `Tables` -> `List Database Tables`
2. `Exec` -> `Exec Database Statement`
3. `Query` -> `Run Database Query`
Also fix tool descriptions to reflect the change from raw markdown output to JSON.
Addresses https://github.com/obot-platform/obot/issues/1208
Since these tools are in the `Capability` category, the "blast radius" of this change includes [the `TableHandler` implementation in obot](https://github.com/obot-platform/obot/blob/31ceab62d455bd798a069be034ea8effb1b41ac4/ui/user/src/lib/components/navbar/Tables.svelte#L8) and all tools/agents currently using them. That being the case, we
should hold-off on merging this change until the `TableHandler` implementation has been …
=> enhance: use more descriptive names for database tools

browser/tool.gpt
Ensure the `Browser` bundle's `Download` tool doesn't interfere with the `Get Page Contents` tool by:
- Renaming the tool to `Download File From URL`
- Updating the description and context to explicitly specify it's for
download binary files
The "blast radius" of this change includes all existing agents and workflows that depend on the current `Download` tool. This means we'll need an additional migration step to update any direct references to the old name -- `Download` -- to `Download Files From URL`.
Addresses https://github.com/obot-platform/obot/issues/1205
=> fix: ensure download tool doesnt interfere with reading webpages

anthropic-bedrock-model-provider/tool.gpt, anthropic-model-provider/tool.gpt, azure-openai-model-provider/tool.gpt, browser/tool.gpt, deepseek-model-provider/tool.gpt, google/youtube/tool.gpt, groq-model-provider/tool.gpt, images/tool.gpt, knowledge/ingest.gpt, knowledge/load.gpt, knowledge/tool.gpt, ollama-model-provider/tool.gpt, openai-model-provider/tool.gpt, vllm-model-provider/tool.gpt, voyage-model-provider/tool.gpt, website-cleaner/tool.gpt, xai-model-provider/tool.gpt
The noAuth metadata field indicates to Obot which tools don't need user authentication.
Issue: https://github.com/obot-platform/obot/issues/1256
=> chore: add noAuth metadata to tools that need it

browser/src/screenshot.ts, images/src/analyze.ts, images/src/generate.ts
Addresses:
- https://github.com/obot-platform/obot/issues/1301
- https://github.com/obot-platform/obot/issues/1259
=> fix: image urls for screenshot and images tools

anthropic-model-provider/anthropic_common/__init__.py, anthropic-model-provider/anthropic_common/api.py, anthropic-model-provider/anthropic_common/helpers.py, anthropic-model-provider/main.py, anthropic-model-provider/requirements.txt, anthropic-model-provider/setup.py, anthropic-model-provider/validate.py
with this we can get rid of https://github.com/gptscript-ai/claude3-provider-common
=> change: move claude3-provider-common code to anthropic-model-provider

knowledge/data-sources/website/colly.go, knowledge/data-sources/website/main.go
The url was not properly added to the memory store to restore scraping process. Also, record pdf files that have been scraped too. 
https://github.com/obot-platform/obot/issues/536
=> Fix: Add visited url properly to memory store

anthropic-model-provider/tool.gpt, deepseek-model-provider/tool.gpt, groq-model-provider/tool.gpt, ollama-model-provider/tool.gpt, openai-model-provider/tool.gpt, placeholder-credential/main.py, placeholder-credential/requirements.txt, placeholder-credential/tool.gpt, vllm-model-provider/tool.gpt, voyage-model-provider/tool.gpt, xai-model-provider/tool.gpt
After this change, running standalone GPTScript with one of these model providers will prompt for the proper credential.
=> enhance: make it easier to run model providers with standalone GPTScript

google/credential/tool.gpt, google/docs/create_doc.py, google/docs/id.py, google/docs/read_doc.py, google/docs/requirements.txt, google/docs/tool.gpt, google/docs/update_doc.py
Addresses https://github.com/obot-platform/obot/issues/1406
=> enhance: add create and write google docs tools

google/search/src/search.ts
Enable Javascript when gathering page content in the `Google Search` tool. This allows more content to be extracted from web pages that require Javascript to load properly.
Addresses part of https://github.com/obot-platform/obot/issues/1423
=> enhance: enable js for google search tool

time/tool.gpt
Having the time tool bundled causes issues with other "utilities." Also, the time tool is just one tool, so we can unbudle it for now.
=> chore: unbundle the time tool

google/docs/update_doc.py
Don't add empty text elements when updating Google Docs. This can break doc updates.
Addresses https://github.com/obot-platform/obot/issues/1477
Note: There's a separate issue with styling on updates for ordered and unordered lists that will be addressed in a follow-up.
=> fix: skip empty elements when updating google docs

docs/auth-providers.md
This is a doc about the requirements that auth provider tools must meet. It didn't make sense to put it in the real Obot documentation, so I put it here instead.
=> docs: auth providers

deepseek-model-provider/main.go, groq-model-provider/main.go, ollama-model-provider/main.go, openai-model-provider/main.go, openai-model-provider/proxy/proxy.go, openai-model-provider/proxy/validate.go, vllm-model-provider/main.go, xai-model-provider/main.go
E.g. Google Gemini Vertex AI has OpenAI API compatibility, but not for everything. /embeddings and /models are not supported, but still we gain the benefit of having /chat/completions and not having to translate the completion requests/responses.
Also, Gemini as the example at hand doesn't use the `/v1` API base.
With the `baseURL` setting we are closer to the settings we have/had in GPTScript and Knowledge
=> enhance: openai-model-provider proxy - combine options into single baseURL and add customPathHandleFuncs for customizability

gitlab/main.go, gitlab/tool.gpt
relates to https://github.com/obot-platform/obot/issues/1422
=> fix: explicit instructions about project_id format

github-auth-provider/main.go, google-auth-provider/main.go
for obot-platform/obot#1488
This should NOT be merged until we are sure that every auth provider's OAuth app is updated to have this as a valid redirect URI.
=> chore: use / for auth provider redirect

google/docs/update_doc.py
Addresses https://github.com/obot-platform/obot/issues/1514#issue-2819292148
Before:
After:
=> fix: formatting for un-ordered lists when updating google docs

google/docs/create_doc.py, google/docs/move_doc.py, google/docs/read_doc.py, google/docs/tool.gpt, google/docs/update_doc.py
Addresses https://github.com/obot-platform/obot/issues/1516
=> enhance: add content param to create google doc tool

atlassian/credential/tool.gpt, atlassian/jira/tool.gpt, github/credential/tool.gpt, github/tool.gpt, knowledge/data-sources/notion/tool.gpt, knowledge/data-sources/onedrive/tool.gpt, oauth2/main.go, oauth2/tool.gpt, slack/credential/tool.gpt, slack/tool.gpt
Tools will now be able to specify, in their metadata, that their OAuth credential supports personal access tokens with the oauthPATSupported field being "true". If a tool does this, then the OAuth credential will prompt the user for a PAT instead of going through the OAuth flow.
This change includes this field on the GitHub and Atlassian tools.
Lastly, this change removes support for OAuth outside Obot. The OAuth credential tool will no longer look at the CLI config nor default to use the Gateway.
Issue: https://github.com/obot-platform/obot/issues/1372
=> feat: add support to use PATs instead of OAuth

google/docs/move_doc.py, google/docs/read_doc.py, google/docs/requirements.txt, google/docs/tool.gpt, google/docs/update_doc.py
Instead of parsing google docs to/from markdown:
- import markdown directly via the APIs
- export docs to markdown via the APIs
This makes formatting more consistent and reduces the complexity of both operations considerably.
Addresses https://github.com/obot-platform/obot/issues/1515
Before:
After:
=> enhance: create and update google docs by importing markdown directly

google/search/tool.gpt
The `Google Search` tool makes unauthenticated requests to google
search with a headless browser. Remove the OAuth metadata from the
tool so it can be used without setting up Google OAuth for tools.
Addresses https://github.com/obot-platform/obot/issues/1548
=> fix: remove oauth metadata from google search tool

.github/workflows/dispatch.yaml
If the corresponding release for Obot already exists, then this won't update or delete it.
=> chore: add the ability for an Obot release to create a release in tools

atlassian/credential/tool.gpt, atlassian/jira/index.js, atlassian/jira/tool.gpt
The Jira API is different for OAuth versus API keys. This change modifies the Jira tool so that it works with API keys and OAuth.
Issue: https://github.com/obot-platform/obot/issues/1555
=> fix: modify Jira tool for API key support

linkedin/main.py, linkedin/tools/helper.py, linkedin/tools/posts.py, linkedin/tools/users.py
**What does this PR do:**
- address issue https://github.com/obot-platform/obot/issues/1567 by adding a retry mechanism to the `get_user()` function.
- address issue https://github.com/obot-platform/obot/issues/1576 by providing a manually crafted link to the post created.
=> fix: Fix LinkedIn get_user() and create_post() method.

database/pkg/cmd/rows.go
Addresses https://github.com/obot-platform/obot/issues/1629
JSON response from tool after change:
```json
{
"columns": [
"name",
"difficulty"
],
"rows": [
{
"difficulty": "Easy",
"name": "Python"
},
{
"difficulty": "Medium",
"name": "JavaScript"
},
{
"difficulty": "Medium",
"name": "Java"
},
{
"difficulty": "Hard",
"name": "C++"
},
{
"difficulty": "Medium",
"name": "Ruby"
},
{
"difficulty": "Medium",
"name": "Swift"
}
]
}
```
and the Obot UI:
=> fix: return correct column names from dedicated table rows tool

outlook/calendar/credential/tool.gpt, outlook/mail/credential/tool.gpt
The outlook credentials had two problems:
1. Not enough dots
2. Imposter syndrome
=> Fix: Correct Outlook credential reference

slack/src/tools.js, slack/tool.gpt
- Convert slack message datetimes to user tz in code
- Improve slack search messages context
Addresses https://github.com/obot-platform/obot/issues/584 again.
=> fix: convert slack message datetimes to user tz in code

google/search/package-lock.json, google/search/package.json, google/search/src/server.ts, google/search/src/session.ts
Properly extract the thread workspace ID from the `X-GPTSCRIPT-ENV` header.
Before this change, the tool would fail to extract it and would fallback on the value set in its environment variables. Since the session ID -- used for managing sessions -- is derived from the extracted workspace ID and the value in the daemon tool's env is static, every thread ended up sharing the same session.
Additionally, redesign session management to:
- use a third-party TTL cache package to handle session expiration and
cleanup
- use session scoped locks to reduce contention when provisioning new
sessions
- remove potential race conditions
Addresses:
- https://github.com/obot-platform/obot/issues/1651
- https://github.com/obot-platform/obot/issues/1653
=> fix: google search workspace id extraction and session management

wordpress/credential/tool.gpt, wordpress/tool.gpt
- Add detailed instructions to the Wordpress tool auth page, includes guidelines of site url format, as well as prerequisites to setup application password & how-to config permalinks to enable API endpoint path. Hopefully this makes the auth setup UX better.
- Notify user that `wordpress.com` sites are NOT supported. We can add more if in the future we found any other platforms are not compatible. https://github.com/obot-platform/obot/issues/1650
I think it would be nice if the UI can display the message in a more structured format.
=> fix: wordpress auth instruction update

wordpress/credential/tool.gpt
=> Fix: Add newline to wordpress cred description

slack/package-lock.json, slack/package.json, slack/src/tools.js
Update the `Search Channels` and `Search Users` tools to use Fuse.js to filter slack channel names and user names by similarity to the query string.
Note: This may not return exact matches, but will allow LLMs to filter the channels and users down to results with similar names.
Addresses https://github.com/obot-platform/obot/issues/1660
=> fix: use fusejs to filter search results for slack channels and users

google/search/package-lock.json, google/search/package.json, google/search/src/headers.ts, google/search/src/refine.ts, google/search/src/search.ts, google/search/src/server.ts, google/search/src/session.ts, google/search/tool.gpt
Improves `Google Search` page loading, scraping, and LLM-based content refinement.
This PR includes the following enhancements:
- Wait for result page DOMs to stabilize -- i.e. no changes for 500ms -- before scraping content
- Do a better job pre-filtering non-content HTML elements before transforming to markdown
- Produce dense/prettified markdown content on the initial scrape
- Use tiktoken to get a more accurate token count for content truncation
- Change content refinement prompt to produce output suitable for truncation (dense markdown instead of JSON)
- Distribute the `Google Search` tool output token budget across results based on their size and the quality of their content when truncating refined search result content (the goal is to keep shorter, higher quality, content as intact …
=> enhance: optimistic search page loading and improved content refinement

wordpress/tool.gpt, wordpress/tools/posts.py
- Prompt the agent to format post with HTML tags, not markdown syntax. https://github.com/obot-platform/obot/issues/1665
- Also change default post status to `draft`.
=> enhance: update prompt to format wordpress post content

oauth2/main.go
there is a `defer` higher up that prints the `credJSON`, so we shouldn't print it again down here.
=> fix: oauth2: only return the credential once

database/pkg/cmd/rows.go
When there are no rows in a table, the `list_database_table_rows` tool doesn't return table column names.
To fix this, use an explicit query to fetch the table columns instead of relying on sqlite3's `-header` option.
Addresses https://github.com/obot-platform/obot/issues/1702
=> fix: always return database table columns

anthropic-model-provider/tool.gpt, atlassian/jira/tool.gpt, bluesky/tool.gpt, browser/tool.gpt, excel/tool.gpt, file-summarizer/tool.gpt, github/tool.gpt, gitlab/tool.gpt, google/docs/tool.gpt, google/gmail/tool.gpt, google/search/tool.gpt, google/sheets/tool.gpt, google/youtube/tool.gpt, images/tool.gpt, index.yaml, linkedin-publishing/tool.gpt, notion/tool.gpt, outlook/calendar/tool.gpt, outlook/mail/tool.gpt, sendgrid/tool.gpt, slack/tool.gpt, word/tool.gpt, wordpress/tool.gpt, zoom/tool.gpt
This pr removes category and `all: true` per https://github.com/obot-platform/obot/issues/1026.
The import logic will be changed in obot to accommodate it.
It doesn't rely on bundle and category metadata anymore. Category can be used to defined bigger group other than bundle.
=> Tool index refactoring

index.yaml, search/tavily/credential/tool.gpt, search/tavily/main.py, search/tavily/requirements.txt, search/tavily/tool.gpt
Simplest possible implementation (i.e. not using any of their [available options](https://docs.tavily.com/sdk/reference/python#parameters))
It will prompt the user for a Tavily API Key - there are 1k free credits per month on Tavily's free plan.
Issue https://github.com/obot-platform/obot/issues/1363
=> add: basic tavily search tool

outlook/mail/pkg/commands/listMessages.go
When no message is found given a folder, the list-message will fail and exit 1 because it can't create dataset with 0 elements. This is to bypass that
=> Fix: return early when no message is found

index.yaml, search/tavily/main.py, search/tavily/safesearch.gpt
https://github.com/obot-platform/obot/issues/1700
The idea is that the UI will set the TAVILY_ALLOWED_DOMAINS* env vars such that the LLM cannot decide the search domains itself.
=> feat: safesearch variant of the tavily search to that only allows searching a limited set of domains

google/credential/tool.gpt, google/search-console/index.js, google/search-console/package-lock.json, google/search-console/package.json, google/search-console/src/keywords.js, google/search-console/src/siteList.js, google/search-console/src/urlInspection.js, google/search-console/src/urlsForProperty.js, google/search-console/tool.gpt
Adds the new tool for Google Search Console
Adds new scopes to the Google Credential
=> chore: add Google Search Console

slack/index.js, slack/src/tools.js, slack/tool.gpt
Add a new tool to support getting a thread using the Slack link from the first message in the thread.
e.g. `https://team.slack.com/archives/CHANNEL_ID/p1234567890123456`
This provides an escape hatch if the LLM has trouble searching for a thread or the user knows exactly which thread they want.
Addresses https://github.com/obot-platform/obot/issues/1753
=> feat: add a new slack tool to get thread messages using a link

database/main.go, database/pkg/cmd/command.go, database/pkg/cmd/context.go, database/pkg/cmd/rows.go, database/pkg/cmd/table.go, database/tool.gpt
Redesign the database tool to accept a single `sql` parameter and hide
the fact that it's running the sqlite3 command under the hood.
Also:
- Remove context to coax LLM into quoting argument strings
- Use the `-json` sqlite3 option to simplify the logic in tools
that drive UI database capabilities
- Don't use shlex
Addresses https://github.com/obot-platform/obot/issues/1734#issue-2850199682
=> fix: redesign database tool to hide sqlite3 cli from llm

wordpress/credential/tool.gpt, wordpress/main.py, wordpress/requirements.txt, wordpress/tool.gpt, wordpress/tools/helper.py, wordpress/tools/media.py, wordpress/tools/posts.py, wordpress/tools/users.py, wordpress/validate-credential.gpt
- use `mistune` library to convert markdown content to html(wordpress format). No more praying to the LLM for the correct format 🥲 https://github.com/obot-platform/obot/issues/1665
- Add a `GetMe` tool to get the role and capabilities of the current user. This tool also used for credential validation, see the `validate-credential.gpt`.
- Add instruction to guide user to locate the correct WordPress Site URL for authentication
- Handle error response status code(401 authorization error and 403 permission error). Add loggers to certain tools to print information to Obot server.
- tweak prompts for some tools
=> enhance: Wordpress - function to guarantee correct post format and bug fix

index.yaml
Regression from https://github.com/obot-platform/tools/pull/425/commits/9a2ff5922ca25103110f46703b47f6be5e67eea7
also adds back tavily which seems to got lost in the same rebase screw-up
=> fix: remove all:true from index.yaml again

google/search-console/tool.gpt
Category is not need anymore to group a bundle tool. Instead it should be optional and should have a bigger scope.
=> Chore: remove category for google search console tool

auth-providers-common/pkg/state/state.go, github-auth-provider/main.go
This is needed for https://github.com/obot-platform/obot/issues/1747
=> fix: github: return user id

openai-model-provider/proxy/validate.go
The generic OpenAI compatible model provider requires that the models list returned have an Object parameter with value "list." This parameter is not included in some otherwise compatible model providers and it seems reasonable to not require this field.
For whatever it's worth: I consider this work to have been done in my free time.
=> fix: allow no object type for model list

google/search/tool.gpt, search/tavily/tool.gpt
This helps distinguish between the search tools being used when events for said
tools are emitted.
=> chore: add tool bundle metadata to search tools

oauth2/main.go, slack/credential/bot.gpt, slack/credential/tool.gpt, slack/tool.gpt
Add support to use slack bot token to send message a bot. This is done by adding a new tool into slack bundle that consumes a separate credential that requests bot token.
=> Enhance: Add support to pull slack bot token

index.yaml, slack/tool-bot.gpt, slack/tool.gpt
Make slack bot tools as a separate bundle tool by consuming bot token credential. This is so that we can avoid the case where we add more bot tools into our existing slack tool cause user to have prompt twice for different credentials requesting user vs bot token.
To minimize the scope of this PR, it is only adding functionality to send DM as Bot. We can extend more tools based on real use case later, like the tools we already have for slack
=> Enhance: Add slack bot tool as a bundle

credential-stores/pkg/common/encryption.go
This change makes it so that the database credential helpers for postgres and sqlite will crash if a non-default encryption config file is set, but the file does not exist. This will help prevent accidental misconfiguration from going unnoticed.
=> fix: database cred helper: crash if encryption config file is missing

credential-stores/pkg/common/encryption.go
For some reason, this log message can cause the Obot server to hang when starting up.
=> fix: database cred helpers: remove log

slack/.prettierrc, slack/index.js, slack/package-lock.json, slack/package.json, slack/src/tools.js
Fix the channel list by using cursor to find the rest of the results, also use formatter to format code properly.
https://github.com/obot-platform/obot/issues/1827
=> Fix: list/search channel properly using cursor

browser/package-lock.json, browser/package.json, browser/src/browse.ts, browser/src/download.ts, browser/src/fill.ts, browser/src/select.ts, browser/src/server.ts, browser/src/session.ts, browser/tool.gpt
Use the model provider credentials injected into the HTTP headers by Obot
to configure GPTScript.
Addresses https://github.com/obot-platform/obot/issues/1855
=> fix: use model provider credentials

wordpress/tool.gpt, zoom/tool.gpt
This PR simply adds a few prompt tweaks I applied during Hackathon to the `tool.gpt` of WordPress and Zoom tool
=> Fix: Apply Hackathon Prompt Tweaks to WordPress And Zoom Tools

zoom/tool.gpt, zoom/tools/helper.py, zoom/tools/meetings.py, zoom/tools/recordings.py
https://github.com/obot-platform/obot/issues/1892
This PR:
- add API to get past meeting instances of a meeting. The information can then be used to get recordings/summaries ..etc
- tweak prompt so agent has aware of date & time
- allow auto-start-ai-summary for meeting creation
- add instructions about instant meetings and personal meeting rooms
- add logger and other minor fix.
=> enhance: add support to get past meeting instances

knowledge/pkg/client/client.go, knowledge/pkg/client/standalone.go, knowledge/pkg/cmd/askdir.go, knowledge/pkg/cmd/ingest.go, knowledge/pkg/datastore/ingest.go, knowledge/pkg/datastore/transformers/metadata.go, knowledge/pkg/flows/flows.go, knowledge/pkg/index/index.go, knowledge/pkg/index/postgres/postgres.go, knowledge/pkg/index/sqlite/sqlite.go, knowledge/pkg/index/types/models.go, knowledge/pkg/index/types/types.go, knowledge/pkg/vectorstore/chromem/chromem.go, knowledge/pkg/vectorstore/pgvector/pgvector.go, knowledge/pkg/vectorstore/sqlite-vec/helper.go, knowledge/pkg/vectorstore/sqlite-vec/sqlite-vec.go, knowledge/pkg/vectorstore/vectorstores.go
- calculate sha256sum for the content of each ingested file and record it in the DB
- when ingesting a file, check if there's a file with the same checksum in the DB
- if yes and the embeddingModel (config on the owning dataset) matches the incoming one, then fetch the file's documents and their embeddings to re-use for the incoming file
NOTE: This is fine in the Obot setup, as we're using a static flow config for Obot, but if someone is playing with the flow config to test different settings, this may lead to reusing documents from file that were ingested with an old config - we can add checks for that as a follow-up.
Also, I figured that there's a race condition in the pgvector implementation, because appending to the pgx batch queue is not lock protected and I saw some cases, where …
=> feat: reuse documents/embeddings for files with the same sha256sum (+fix pgx bug)

bluesky/package-lock.json, bluesky/package.json, bluesky/src/embed.ts, bluesky/src/posts.ts, bluesky/src/tools.ts, bluesky/tool.gpt
Links and tags in posts created by the `Bluesky` bundle's `Create Post`
tool are not being rendered correctly on bsky.app. This is because the
posts were missing metadata that Bluesky requires to render them.
To correct this, resolve and include the missing metadata with posts.
e.g. Before this change
e.g. After
Addresses https://github.com/obot-platform/obot/issues/1960
=> fix: bsky create post link and tag formatting

vllm-model-provider/tool.gpt
vLLM doesn't require specifying an API Key
New:
Issue: https://github.com/obot-platform/obot/issues/1967
=> chore: make API Key param optional for vLLM

images/src/analyze.ts, images/src/generate.ts
Workspace files stored in the `files` directory are now served at `/api/threads/{threadId}/file/{file_name}` (`/file/` singular) instead of `/api/threads/{threadId}/files/{file_name}` (`/files/` plural). Update the `Generate Images` and
`Analyze Images` tools to comply with this change.
This fixes broken generated image links in the UI and when analyzing
them.
Addresses https://github.com/obot-platform/obot/issues/2005
=> fix: generated image download path

browser/src/screenshot.ts
The path to access workspace files from the UI has changed slightly,
which breaks the links currently produced by the `Screenshot` tool.
Update the download URLs produced by the `Screenshot` tool to account
for the change.
Addresses https://github.com/obot-platform/obot/issues/2059
=> fix: screenshot download path

word/pkg/graph/docs.go
Issue: https://github.com/obot-platform/obot/issues/1792
Before and After (compiled new tool in between):
=> fix: word_write: onedrive path . means root

word/pkg/commands/list.go
Issue: https://github.com/obot-platform/obot/issues/1791 (not a fix, but related)
=> fix: word/list: handle dataset create error

workspace-files/main.go, workspace-files/tool.gpt
https://github.com/obot-platform/obot/issues/1986
=> fix: update workspace read/write method, so it's clear it only supports plain text format

credential-stores/sqlite/main.go
This fixes an issue when running obot locally with sqlite. Credentials are stored in a separate database file from the rest of obot when running this way, meaning that this table never gets created by the main obot process, causing the credential helpers to always just return errors.
=> fix: cred helpers: sqlite: automigrate the gptscript_credentials table

bluesky/tool.gpt, browser/tool.gpt, github/tool.gpt, google/gmail/tool.gpt, google/search/tool.gpt, linkedin-publishing/tool.gpt, outlook/calendar/tool.gpt, outlook/mail/tool.gpt, search/google/googlecustomsearch/tool.gpt, search/tavily/tool.gpt, search/tavily/websiteknowledge.gpt, slack/tool.gpt, wordpress/tool.gpt, zoom/tool.gpt
The time context tools are shared by the Time bundle, which is included as `Optional - On` by the default Obot.
Addresses https://github.com/obot-platform/obot/issues/2039
=> chore: remove shared time context from tools

outlook/mail/tool.gpt
Addresses https://github.com/obot-platform/obot/issues/583
Note: The search was working properly in the case explained in the referenced issue, but the dates were being displayed in UTC. This change consistently fixed that issue for me. I also tried an output filter, but it wasn't clear if that actually helped _more_ than just rewording the context.
=> fix: use preferred timezone to display outlook message dates

google/calendar/main.py, google/calendar/tool.gpt, google/calendar/tools/event.py, google/calendar/tools/helper.py
https://github.com/obot-platform/obot/issues/2042
This PR:
- adds a `Respond to Event` tool to the Google Calendar Tool, allowing users to respond to pending calendar invitations.
- make sure only the Event Organizer can `update` an event. Even attendees can only update their own copies of events anyway, but this will make it less confusing.
=> feat: add respond_to_event tool to google calendar, update `Update Event`

google/gmail/helpers.py
Dates in the gmail API are interpreted as PST unless timestamps are used. Add code-based formatting to replace query dates with accurate timestamps based on the user's preferred timezone before calling the API.
Addresses https://github.com/obot-platform/obot/issues/518
=> fix: replace gmail query dates with unix timestamps

google/calendar/tool.gpt, google/calendar/tools/event.py
https://github.com/obot-platform/obot/issues/2328
- handle the case when the recurrence rule is not a json array.
- Return a clear error message when the agent attempts to update a property that exists on the event, but is not updatable for its eventType according to the Google Calendar API.
- preserve full metadata of existing attendees when updating an event.
=> Fix: Google calendar Tool bugfix

slack/credential/bot.gpt, slack/tool-bot.gpt
This PR adds more slack bot tools so that the bot can do more things like send message to channels, list channels. It will also request more scopes.
Search message from slack tool is not added because it is not supported by the bot.
=> Enhance: Add more slack bot tools

zoom/tool.gpt, zoom/tools/meetings.py
This PR to address issue comments: https://github.com/obot-platform/obot/issues/1892#issuecomment-2770813691
- removed meeting series UUIDs from the API responses. This helps the Obot agent to find the correct meeting UUID to get AI meeting summaries.
- Other prompts fixes.
=> fix: removed useless meeting series UUIDs in APIresponses from Zoom Tool

outlook/mail/pkg/commands/listGroups.go, outlook/mail/pkg/graph/group.go
To address issue comment : https://github.com/obot-platform/obot/issues/1940#issuecomment-2754881365
Guest users within a Microsoft organization are restricted from accessing Groups features.
=> fix: detect userType and return Proper error message when user has no permission

anthropic-model-provider-go/go.mod, anthropic-model-provider-go/go.sum, anthropic-model-provider-go/main.go, anthropic-model-provider-go/proxy/models.go, anthropic-model-provider-go/proxy/proxy.go, anthropic-model-provider-go/tool.gpt, index.yaml, openai-model-provider/proxy/proxy.go, openai-model-provider/proxy/validate.go
We cannot replace the Python implementation yet since the anthropic-bedrock provider is still relying on it.
Issue: https://github.com/obot-platform/obot/issues/1999
=> feat: rewrite anthropic-model-provider as openai-style proxy in Go and add thinking mode

google/calendar/tool.gpt, google/calendar/tools/event.py
- Update the prompt for Obot --  `json array of strings` instead of `json array`, reduce the possibility of LLM making mistakes. The LLM will now more likely to generate an array like `[ "RRULE:FREQ=YEARLY"]` instead of a string like `"[\"RRULE:FREQ=YEARLY\"]"`
- add one line of code to try to fix bad input.
=> fix: Google calendar recurrence rule string

google/youtube/requirements.txt
Fix mismatch dependency.
```
#31 114.9 ++ hash -r
#31 114.9 + find obot-tools -name requirements.txt -exec cat '{}' ';' -exec echo ';'
#31 114.9 + sort -u
#31 115.2 + uv pip install -r requirements.txt
#31 115.3 Using Python 3.13.2 environment at: obot-tools/venv
#31 115.5   × No solution found when resolving dependencies:
#31 115.5   ╰─▶ Because you require typing-extensions==4.12.2 and
#31 115.5       typing-extensions==4.13.1, we can conclude that your requirements are
#31 115.5       unsatisfiable.
```
https://github.com/obot-platform/obot/actions/runs/14250628637
=> Fix: fix python dependency

tasks-workflow/tool.gpt
This return parameter allows the LLM to provide more context as to why the task is being aborted.
=> enhance: add a return parameter when aborting the current task

outlook/mail/pkg/commands/listGroups.go, outlook/mail/pkg/graph/group.go
https://github.com/obot-platform/obot/issues/1940#issuecomment-2779420058
- When userType is `nil` it is a Personal Account
- which also doesn't have permission to the Group features.
=> fix: handle personal account type for Outlook Mail Groups

google-auth-provider/go.mod, google-auth-provider/go.sum
This should give me better information that I can use to troubleshoot the seemingly random session deletion that we occasionally see. I pushed a commit to our oauth2-proxy fork that logs every time a session is deleted from the database, as well as the hash of the username and email to whom the session belonged.
=> chore: google auth provider: bump oauth2-proxy dependency for better logging

slack/credential/bot.gpt
Fix a typo in slack permission
=> Fix: fix slack permission typo

outlook/mail/pkg/commands/listGroupThreads.go, outlook/mail/pkg/commands/listGroups.go, outlook/mail/pkg/graph/group.go, outlook/mail/pkg/util/util.go, outlook/mail/tool.gpt
I needed datasets here for a use case I am working on, so I added them. I also fixed an issue around listing group emails, because the Graph API does not let you filter by start and end for that API method, so we have to filter after instead.
=> fix: outlook mail: use datasets where needed, fix date filters

file-summarizer/tools/load_text.py
for https://github.com/obot-platform/obot/issues/2096
The knowledge tool checks the `OPENAI_MODEL` environment variable to determine the model to use. So rename `OBOT_DEFAULT_VISION_MODEL` and pass to it.
=> fix: the correct env to config for knowledge tool

google-auth-provider/go.mod, google-auth-provider/go.sum
This should help me with https://github.com/obot-platform/obot/issues/2444.
Pulling in changes from this commit: https://github.com/obot-platform/oauth2-proxy/commit/04ef7cc9eb092dc2eb138ea5bc9f0880ec9962d2
=> chore: google auth provider: bump oauth2-proxy dependency for more logs

workspace-files/main.go, workspace-files/tool.gpt
Add a tool that lets the LLM get the download URL for a workspace file
=> Enhance: Download URLs for workpsace files

index.yaml, microsoft365/outlook/mail/main.go, microsoft365/outlook/mail/pkg/commands/createDraft.go, microsoft365/outlook/mail/pkg/commands/createGroupThreadEmail.go, microsoft365/outlook/mail/pkg/commands/deleteEmail.go, microsoft365/outlook/mail/pkg/commands/downloadAttachment.go, microsoft365/outlook/mail/pkg/commands/getEmailDetails.go, microsoft365/outlook/mail/pkg/commands/getGroupThreadEmailAttachment.go, microsoft365/outlook/mail/pkg/commands/listAttachments.go, microsoft365/outlook/mail/pkg/commands/listEmails.go, microsoft365/outlook/mail/pkg/commands/listGroupThreadEmailAttachments.go, microsoft365/outlook/mail/pkg/commands/moveEmail.go, microsoft365/outlook/mail/pkg/commands/readAttachment.go, microsoft365/outlook/mail/pkg/commands/searchEmails.go, microsoft365/outlook/mail/pkg/graph/mail.go, microsoft365/outlook/mail/tool.gpt
This replaces the words "message" and "post" with "email" throughout all the Outlook Mail tools, as that should be less confusing for the user and for the LLM. I also made sure to mention something about Outlook or MS365 in the descriptions for each of these tools.
=> chore: improve outlook mail tool names and descriptions

anthropic-model-provider-go/main.go, anthropic-model-provider-go/proxy/proxy.go, openai-model-provider/proxy/proxy.go, tests/tool_test.go
This change also removes the old python-based Anthropic model provider because it isn't being used anymore. Lastly, some simplifications to the OpenAI proxy are made.
=> enhance: add token usage to Anthropic model provider

google/gmail/apis/helpers.py, google/gmail/apis/labels.py, google/gmail/apis/messages.py, google/gmail/commands/__init__.py, google/gmail/commands/create_label.py, google/gmail/commands/delete_label.py, google/gmail/commands/list_emails.py, google/gmail/commands/list_labels.py, google/gmail/commands/modify_message_labels.py, google/gmail/commands/update_label.py, google/gmail/main.py, google/gmail/readEmail.py, google/gmail/tool.gpt
This PR:
- adds CRUD custom label tools to gmail bundle https://github.com/obot-platform/obot/issues/2590. Note: the list_labels tool will only display custom labels, and hide system/internal gmail labels.
- A new tool `Modify Email Labels` to support applying labels to gmail email: https://github.com/obot-platform/obot/issues/2591
- mark email as read/unread
- archive email
- mark/remove email as starred
- mark/remove email as important
- apply/remove custom labels to email
- User can move email to a label(archive email automatically ) or apply label to email
- Show read/unread status, show categories(only if email in INBOX) in metadata when listing emails.
- Rename `List Inbox` to `List Emails`.
=> feat: Gmail support CRUD labels and support apply/remove labels to emails

browser/package-lock.json, browser/package.json, browser/src/download.ts, browser/src/server.ts, browser/tool.gpt
for https://github.com/obot-platform/obot/issues/2604
=> enhance: browser: combine get and download tools

microsoft365/outlook/calendar/main.go, microsoft365/outlook/calendar/pkg/printers/events.go
fix the bug sangeetha found https://github.com/obot-platform/obot/issues/2644#issuecomment-2831604273
and https://github.com/obot-platform/obot/issues/2643
Timezone database information is often not available in minimal Docker environment operating systems, so it needs to be imported into the Go binary using import _ \"time/tzdata\".
=> fix: include tzdata for golang timezone

microsoft365/outlook/calendar/main.go, microsoft365/outlook/calendar/pkg/commands/deleteEvent.go, microsoft365/outlook/calendar/pkg/commands/getEventAttachments.go, microsoft365/outlook/calendar/pkg/commands/listEvents.go, microsoft365/outlook/calendar/pkg/commands/searchEvents.go, microsoft365/outlook/calendar/pkg/graph/calendar.go, microsoft365/outlook/calendar/pkg/graph/events.go, microsoft365/outlook/calendar/pkg/graph/groups.go, microsoft365/outlook/calendar/tool.gpt
https://github.com/obot-platform/obot/issues/2642
This PR adds a new Optional Param -- `delete_series` to the `DeleteEvent` Tool. set this to `true` to delete a event series.
Many files changed because I ran `go fmt` 😓
=> feat: support deletion of event series.

anthropic-model-provider-go/main.go, anthropic-model-provider-go/proxy/proxy.go, deepseek-model-provider/main.go, generic-openai-model-provider/main.go, groq-model-provider/main.go, ollama-model-provider/main.go, openai-model-provider/main.go, openai-model-provider/openaiproxy/proxy.go, openai-model-provider/proxy/proxy.go, placeholder-credential/main.py, vllm-model-provider/main.go, xai-model-provider/main.go
The model providers have been changed to support user's personal tokens. If configuration for the environment variables has been provided via special headers, then the model providers will use that configuration instead of the "global" configuration. Additionally, the model providers have been changed to be able to start up without configuration so that they can be used only with a user's individual configuration.
=> enhance: update model providers to support personal tokens

microsoft365/outlook/mail/tool.gpt
Looks like this line got accidentally changed/removed a little while ago.
for https://github.com/obot-platform/obot/issues/2759
=> fix: outlook: fix credential on getting group email attachments

microsoft365/onedrive/main.go, microsoft365/onedrive/pkg/commands/addPermission.go, microsoft365/onedrive/pkg/commands/listSharedWithMeItems.go, microsoft365/onedrive/pkg/graph/driveItem.go, microsoft365/onedrive/pkg/printer/printDrive.go, microsoft365/onedrive/tool.gpt
- display information for sharedwithme Items. show driveID so can be used for downloading. this is for [this ](https://github.com/obot-platform/obot/issues/2861) and [this](https://github.com/obot-platform/obot/issues/2861)
- print  drive's web URL. [issue](https://github.com/obot-platform/obot/issues/2870)
- add permissions with right roles. for [this](https://github.com/obot-platform/obot/issues/2863)
=> fix: OneDrive tool fixes

memory/main.go
Ignore 403 errors when listing memories to prevent it from causing
local-authenticate calls from failing.
Addresses https://github.com/obot-platform/obot/issues/2931
=> fix: memory tool causes 403s on local-authenticate

github/index.js, github/src/tools.js, github/tool.gpt
Added the ability to create and list branches to the tools.
Added the ability to list files and directories.
Added the ability to change files/create update files.
Added ability to delete files.
=> chore: add branch and files support

openai-model-provider/proxy/rewrite.go, xai-model-provider/main.go
https://github.com/obot-platform/obot/issues/2678
Fix xai model provider that doesn't have image-generation usage.
=> Fix: add model for image generation

index.yaml
Dropping google-search (browser based search) and googlecustomsearch
from the index because we dont want to expose these in our MCP server
catalog. I didnt delete the code for these tools becasue I think its
useful to keep them around. Like, you could added the google-search
locally as a custom tool so that it shows up for you locally.
=> Chore: Drop google search tools

microsoft365/outlook/mail/tool.gpt
for https://github.com/obot-platform/obot/issues/2787
I tried getting email details several times for a group email with these changes, and it worked every time. It also worked every time for getting the details of a non-group email still. So I think this is good.
=> fix: outlook mail: get email details: be more specific in param descriptions

microsoft365/outlook/mail/main.go, microsoft365/outlook/mail/pkg/commands/downloadOneDriveShareLink.go, microsoft365/outlook/mail/pkg/global/global.go, microsoft365/outlook/mail/pkg/graph/shares.go, microsoft365/outlook/mail/tool.gpt
for https://github.com/obot-platform/obot/issues/2625
Since these "OneDrive attachments" that can appear in emails are actually just OneDrive share links, I added a tool to the Outlook Mail bundle to download them, the same way we download normal files in the OneDrive tools.
=> enhance: outlook mail: add tool to download files from onedrive share links

microsoft365/outlook/calendar/main.go, microsoft365/outlook/calendar/pkg/client/client.go, microsoft365/outlook/calendar/pkg/commands/listEvents.go, microsoft365/outlook/calendar/pkg/commands/searchEvents.go, microsoft365/outlook/calendar/pkg/graph/calendar.go, microsoft365/outlook/calendar/pkg/printers/events.go, microsoft365/outlook/calendar/tool.gpt
- list events order by time: https://github.com/obot-platform/obot/issues/2741
- list events support `calendar_ids` and `limit`. So it doesn't always have to return events from all calendars. https://github.com/obot-platform/obot/issues/2747
=> fix: Outlook calendar list events

gemini/image-generator.gpt
Convert the `Gemini Image Generator` from a stand-alone tool to a bundle with MCP metadata so that it shows up in Obot's MCP Server catalog.
Also add a context tool with instructions for properly rendering generated images. This matches the pattern in the OpenAI `Images` bundle.
=> chore: convert gemini image generator to a bundle

credential-stores/postgres/main.go, credential-stores/sqlite/main.go
Apparently Docker's libraries fill in the body with `unused` if it's unused, which was leading to an error here that we don't want.
=> fix: cred helpers: don't attempt to parse 'unused' as a list of contexts

auth-providers-common/pkg/state/state.go, github-auth-provider/Makefile, github-auth-provider/go.mod, github-auth-provider/go.sum, github-auth-provider/main.go, github-auth-provider/pkg/profile/profile.go, github-auth-provider/pkg/profile/profile_test.go
- Add the `/obot-list-auth-group` endpoint to the github auth provider
to support searching for a user's org/teams
- Enrich `/obot-get-state` response to include orgs/teams data
=> enhance: expose github auth group data

workspace-files/main.go, workspace-files/tool.gpt
Remove project scope parameters and context from workspace-files tools.
This will prevent the LLM from accidentally writing to/reading from the
project workspace. Leave the core project-scoped login in case we decide
to revive the feature down the road.
Addresses https://github.com/obot-platform/obot/issues/3555
=> chore: remove project scope options from workspace-files

google/gmail/pyproject.toml, google/gmail/uv.lock, microsoft365/outlook-mcp/pyproject.toml, microsoft365/outlook-mcp/uv.lock
the issue I submitted to FastMCP https://github.com/jlowin/fastmcp/issues/1233#issuecomment-3116220840 has been fixed in the latest release, so now we change the dependency back to FastMCP.
=> fix: bump to fastMCP latest version that supports custom http headers

github-auth-provider/main.go, github-auth-provider/pkg/profile/profile.go, github-auth-provider/tool.gpt
- remove teams and repo config from github-auth-provider
- elide github orgs and teams from group search based on restricted orgs config
Addresses:
- https://github.com/obot-platform/obot/issues/4030
- https://github.com/obot-platform/obot/issues/4027
- part of https://github.com/obot-platform/obot/issues/4029
=> Simplify github auth provider config

github-auth-provider/main.go
Fixes a panic that occurs in the github-auth-provider when no GitHub organization option is provided at startup.
Addresses https://github.com/obot-platform/obot/issues/4048
=> fix: panic when no org is provided for the github auth provider

auth-providers-common/pkg/state/state.go
Return the OIDC ID token when getting the state from an oauth provider.
This exposes the ID token to dependent auth provider implementations
so they can extract whatever info they need from them.
=> enhance: return id token from get state
